MapServer -> LMDB: depends on
LMDB -> LCG: depends on
MapServer -> JavascriptObjectNotationExtensions: depends on
MapServer -> XmlErgonomics: depends on
MapServer -> InforSecrets: depends on
MapServer -> PowershellErgonomics: depends on
MapServer -> processExecution: depends on
MapServer -> HtmlErgonomics: depends on
