commonplace\:USAAClassicCheckingAccountCurrentBalance -> 6961.93^^xsd\:decimal : fibo-fnd-acc-cur\:hasAmount
commonplace\:WellsFargoEverydayCheckingAccount -> fibo-fbc-pas-caa\:DemandDepositAccount : rdf\:type
commonplace\:USAAClassicCheckingAccount -> commonplace\:USAAClassicCheckingAccountCurrentBalance : commonplace\:hasCurrentBalance
commonplace\:eristocrates -> foaf\:Person : rdf\:type
commonplace\:USAAClassicSavingsAccount -> commonplace\:USAAClassicSavingsAccountCurrentBalance : commonplace\:hasCurrentBalance
commonplace\:USAAClassicSavingsAccountAvailableBalance -> fibo-fnd-acc-4217\:USDollar : fibo-fnd-acc-cur\:hasCurrency
commonplace\:syrislove -> syrislove^^xsd\:string : foaf\:nick
commonplace\:USAAClassicSavings -> https\://www.usaa.com/banking/savings : rdfs\:seeAlso
commonplace\:USAAClassicSavingsAccount -> lei\:C5654JQHZUHN0772B561 : cmns-org\:isProvidedBy
commonplace\:CrewFinanceCheckingAccountCurrentBalance -> fibo-fnd-acc-4217\:USDollar : fibo-fnd-acc-cur\:hasCurrency
commonplace\:USAAClassicSavingsAccountAvailableBalance -> commonplace\:AvailableBalance : rdf\:type
commonplace\:USAAClassicSavingsAccountCurrentBalance -> fibo-fnd-acc-4217\:USDollar : fibo-fnd-acc-cur\:hasCurrency
commonplace\:eristocrates -> eristocrates^^xsd\:string : foaf\:nick
commonplace\:CrewFinanceCheckingAccount -> lei\:549300JEBULFT3BSU682 : cmns-org\:isProvidedBy
commonplace\:CrewFinanceChecking -> fibo-fbc-fct-fse\:BankingProduct : rdf\:type
commonplace\:USAAClassicSavings -> fibo-fbc-fct-fse\:BankingProduct : rdf\:type
commonplace\:syrislove -> Fisher^^xsd\:string : foaf\:lastName
commonplace\:WellsFargoEverydayCheckingAccountCurrentBalance -> fibo-fnd-acc-4217\:USDollar : fibo-fnd-acc-cur\:hasCurrency
commonplace\:USAAClassicCheckingAccountAvailableBalance -> 2026-09-06T23\:30\:16.5815921-04\:00^^xsd\:dateTimeStamp : cmns-dt\:hasObservedDateTime
commonplace\:eristocrates -> Collier^^xsd\:string : foaf\:lastName
commonplace\:syrislove -> https\://myfuelmaster.com/ : foaf\:workplaceHomepage
commonplace\:USAAClassicSavingsAccount -> commonplace\:USAAClassicSavingsAccountAvailableBalance : commonplace\:hasAvailableBalance
commonplace\:USAAClassicCheckingAccount -> commonplace\:syrislove : fibo-fnd-rel-rel\:isHeldBy
commonplace\:WellsFargoEverydayCheckingAccountAvailableBalance -> 1149.39^^xsd\:decimal : fibo-fnd-acc-cur\:hasAmount
commonplace\:syrislove -> Tierra^^xsd\:string : foaf\:firstName
commonplace\:eristocrates -> https\://cms.leoncountyfl.gov/Government/Departments/Information-and-Technology/Office-of-Information-Technology : foaf\:workplaceHomepage
commonplace\:CrewFinanceCheckingAccount -> commonplace\:CrewFinanceCheckingAccountCurrentBalance : commonplace\:hasCurrentBalance
commonplace\:CrewFinanceCheckingAccountAvailableBalance -> 1040.67^^xsd\:decimal : fibo-fnd-acc-cur\:hasAmount
commonplace\:WellsFargoEverydayCheckingAccount -> lei\:KB1H1DSPRFMYMCUFXT09 : cmns-org\:isProvidedBy
commonplace\:WellsFargoEverydayCheckingAccountAvailableBalance -> 2026-09-06T23\:30\:16.5815921-04\:00^^xsd\:dateTimeStamp : cmns-dt\:hasObservedDateTime
commonplace\:syrislove -> Fisher^^xsd\:string : foaf\:surname
commonplace\:USAAClassicSavingsAccount -> fibo-fbc-pas-caa\:DepositAccount : rdf\:type
commonplace\:USAAClassicChecking -> fibo-fbc-fct-fse\:BankingProduct : rdf\:type
commonplace\:USAAClassicCheckingAccountAvailableBalance -> fibo-fnd-acc-4217\:USDollar : fibo-fnd-acc-cur\:hasCurrency
commonplace\:syrislove -> Fisher^^xsd\:string : foaf\:familyName
commonplace\:USAAClassicCheckingAccountAvailableBalance -> commonplace\:AvailableBalance : rdf\:type
commonplace\:CrewFinanceCheckingAccount -> fibo-fbc-pas-caa\:DemandDepositAccount : rdf\:type
commonplace\:eristocrates -> Brandon^^xsd\:string : foaf\:firstName
commonplace\:eristocrates -> Collier^^xsd\:string : foaf\:surname
commonplace\:WellsFargoEverydayCheckingAccount -> commonplace\:WellsFargoEverydayCheckingAccountCurrentBalance : commonplace\:hasCurrentBalance
commonplace\:USAAClassicSavingsAccount -> commonplace\:syrislove : fibo-fnd-rel-rel\:isHeldBy
commonplace\:CrewFinanceCheckingAccountAvailableBalance -> 2026-09-06T23\:30\:16.5815921-04\:00^^xsd\:dateTimeStamp : cmns-dt\:hasObservedDateTime
commonplace\:eristocrates -> Collier^^xsd\:string : foaf\:familyName
commonplace\:CrewFinanceCheckingAccountCurrentBalance -> 1040.67^^xsd\:decimal : fibo-fnd-acc-cur\:hasAmount
commonplace\:WellsFargoEverydayChecking -> https\://www.wellsfargo.com/checking/everyday : rdfs\:seeAlso
commonplace\:AvailableBalance -> fibo-fbc-pas-caa\:Balance : rdfs\:subClassOf
commonplace\:WellsFargoEverydayCheckingAccount -> commonplace\:WellsFargoEverydayChecking : fibo-fnd-rel-rel\:exemplifies
commonplace\:syrislove -> https\://myfuelmaster.com/job/desktop-support-technician-8 : foaf\:workInfoHomepage
commonplace\:WellsFargoEverydayCheckingAccountAvailableBalance -> fibo-fnd-acc-4217\:USDollar : fibo-fnd-acc-cur\:hasCurrency
commonplace\:hasAvailableBalance -> fibo-fbc-pas-caa\:hasBalance : rdfs\:subPropertyOf
commonplace\:USAAClassicCheckingAccount -> commonplace\:USAAClassicChecking : fibo-fnd-rel-rel\:exemplifies
commonplace\:USAAClassicSavingsAccountAvailableBalance -> 1965.38^^xsd\:decimal : fibo-fnd-acc-cur\:hasAmount
commonplace\:WellsFargoEverydayCheckingAccountAvailableBalance -> commonplace\:AvailableBalance : rdf\:type
commonplace\:eristocrates -> 35^^xsd\:int : foaf\:age
commonplace\:hasCurrentBalance -> fibo-fbc-pas-caa\:hasBalance : rdfs\:subPropertyOf
commonplace\:WellsFargoEverydayCheckingAccount -> commonplace\:WellsFargoEverydayCheckingAccountAvailableBalance : commonplace\:hasAvailableBalance
commonplace\:USAAClassicCheckingAccountAvailableBalance -> 6961.93^^xsd\:decimal : fibo-fnd-acc-cur\:hasAmount
commonplace\:USAAClassicCheckingAccountCurrentBalance -> 2026-09-06T23\:30\:16.5815921-04\:00^^xsd\:dateTimeStamp : cmns-dt\:hasObservedDateTime
commonplace\:CrewFinanceCheckingAccount -> commonplace\:CrewFinanceCheckingAccountAvailableBalance : commonplace\:hasAvailableBalance
commonplace\:USAAClassicCheckingAccountCurrentBalance -> commonplace\:CurrentBalance : rdf\:type
commonplace\:USAAClassicSavingsAccountCurrentBalance -> 1965.38^^xsd\:decimal : fibo-fnd-acc-cur\:hasAmount
commonplace\:USAAClassicCheckingAccount -> lei\:C5654JQHZUHN0772B561 : cmns-org\:isProvidedBy
commonplace\:WellsFargoEverydayCheckingAccountCurrentBalance -> 1149.39^^xsd\:decimal : fibo-fnd-acc-cur\:hasAmount
commonplace\:eristocrates -> https\://www.governmentjobs.com/careers/leoncountyfl/classspecs/1183950 : foaf\:workInfoHomepage
commonplace\:CurrentBalance -> fibo-fbc-pas-caa\:Balance : rdfs\:subClassOf
commonplace\:USAAClassicSavingsAccountAvailableBalance -> 2026-09-06T23\:30\:16.5815921-04\:00^^xsd\:dateTimeStamp : cmns-dt\:hasObservedDateTime
commonplace\:USAAClassicChecking -> https\://www.usaa.com/banking/checking : rdfs\:seeAlso
commonplace\:CrewFinanceCheckingAccountAvailableBalance -> fibo-fnd-acc-4217\:USDollar : fibo-fnd-acc-cur\:hasCurrency
commonplace\:CrewFinanceCheckingAccountCurrentBalance -> commonplace\:CurrentBalance : rdf\:type
commonplace\:CrewFinanceCheckingAccountCurrentBalance -> 2026-09-06T23\:30\:16.5815921-04\:00^^xsd\:dateTimeStamp : cmns-dt\:hasObservedDateTime
commonplace\:syrislove -> foaf\:Person : rdf\:type
commonplace\:USAAClassicCheckingAccount -> commonplace\:USAAClassicCheckingAccountAvailableBalance : commonplace\:hasAvailableBalance
commonplace\:CrewFinanceCheckingAccountAvailableBalance -> commonplace\:AvailableBalance : rdf\:type
commonplace\:CrewFinanceChecking -> https\://www.trycrew.com/pdfjs/web/viewer?file=%2Fdocs%2Fdeposit-agreement.pdf#h.g82ej3s9bgif : rdfs\:seeAlso
commonplace\:syrislove -> commonplace\:eristocrates : foaf\:knows
commonplace\:WellsFargoEverydayChecking -> fibo-fbc-fct-fse\:BankingProduct : rdf\:type
commonplace\:USAAClassicSavingsAccountCurrentBalance -> commonplace\:CurrentBalance : rdf\:type
commonplace\:USAAClassicSavingsAccountCurrentBalance -> 2026-09-06T23\:30\:16.5815921-04\:00^^xsd\:dateTimeStamp : cmns-dt\:hasObservedDateTime
commonplace\:USAAClassicCheckingAccount -> fibo-fbc-pas-caa\:DemandDepositAccount : rdf\:type
commonplace\:WellsFargoEverydayCheckingAccount -> commonplace\:eristocrates : fibo-fnd-rel-rel\:isHeldBy
commonplace\:USAAClassicSavingsAccount -> commonplace\:USAAClassicSavings : fibo-fnd-rel-rel\:exemplifies
commonplace\:WellsFargoEverydayCheckingAccountCurrentBalance -> commonplace\:CurrentBalance : rdf\:type
commonplace\:WellsFargoEverydayCheckingAccountCurrentBalance -> 2026-09-06T23\:30\:16.5815921-04\:00^^xsd\:dateTimeStamp : cmns-dt\:hasObservedDateTime
commonplace\:CrewFinanceCheckingAccount -> commonplace\:CrewFinanceChecking : fibo-fnd-rel-rel\:exemplifies
commonplace\:eristocrates -> commonplace\:syrislove : foaf\:knows
commonplace\:CrewFinanceCheckingAccount -> commonplace\:eristocrates : fibo-fnd-rel-rel\:isHeldBy
commonplace\:syrislove -> 33^^xsd\:int : foaf\:age
commonplace\:USAAClassicCheckingAccountCurrentBalance -> fibo-fnd-acc-4217\:USDollar : fibo-fnd-acc-cur\:hasCurrency