mindmap
  root((Activities))
          Laundry
            Deadline
              Kind : Soft
              Time: Today
            Tasks
              Antecedent
                Sorted laundry
                  Kind : Foreground
                  Targets
                    My laundry
                    Tierras's Laundry
                      Shirts
                      Pants
                      Underwear
                      Jackets
                    Socks
                    Bed Linens
                    Kitchen+Bath Linens
                  Eta : 1hr
              Medial
                Washer Cycle
                  kind : Background
                Activity
                   

                  Dryer Cycle
                Eta : 1hr
              Succeedent
                Kind : Foreground
                Activity


          Medicine
            Deadline
              Kind : Hard
              Time : 6PM
            Process
              Antecedent
                Kind : Fore
          Groceries

