commonplace\:eristocrates -> eristocrates^^xsd\:string : foaf\:nick
wellsFargoAccount\:everydayChecking -> fibo-loan-spc-crd\:DebitCardAccount : rdf\:type
usaaAccount\:usaaSavings -> commonplace\:syrislove : fibo-fbc-pas-caa\:AccountHolder
usaaAccount\:platinumVisa -> fibo-loan-spc-crd\:CreditCardAccount : rdf\:type
commonplace\:eristocrates -> governmentjobs\:1183950 : foaf\:workInfoHomepage
commonplace\:eristocrates -> 35^^xsd\:int : foaf\:age
commonplace\:syrislove -> Fisher^^xsd\:string : foaf\:familyName
commonplace\:syrislove -> Tierra^^xsd\:string : foaf\:firstName
wellsFargoAccount\:wellsFargoRewards -> commonplace\:eristocrates : fibo-fbc-pas-caa\:AccountHolder
commonplace\:syrislove -> fuelmasterjob\:desktop-support-technician-8 : foaf\:workInfoHomepage
wellsFargoAccount\:platinumCard -> fibo-loan-spc-crd\:CreditCardAccount : rdf\:type
wellsFargoAccount\:everydayChecking -> commonplace\:eristocrates : fibo-fbc-pas-caa\:AccountHolder
wellsFargoAccount\:wellsFargoRewards -> fibo-fbc-pas-caa\:Account : rdf\:type
commonplace\:eristocrates -> Collier^^xsd\:string : foaf\:familyName
commonplace\:syrislove -> 33^^xsd\:int : foaf\:age
usaaAccount\:checking -> fibo-loan-spc-crd\:DebitCardAccount : rdf\:type
wellsFargoAccount\:platinumCard -> commonplace\:eristocrates : fibo-fbc-pas-caa\:AccountHolder
commonplace\:syrislove -> commonplace\:eristocrates : foaf\:knows
commonplace\:eristocrates -> Collier^^xsd\:string : foaf\:surname
commonplace\:eristocrates -> Brandon^^xsd\:string : foaf\:firstName
commonplace\:syrislove -> foaf\:Person : rdf\:type
commonplace\:syrislove -> https\://myfuelmaster.com/^^xsd\:anyURI : foaf\:workplaceHomepage
usaaAccount\:usaaSavings -> fibo-fbc-pas-caa\:DepositAccount : rdf\:type
commonplace\:syrislove -> Fisher^^xsd\:string : foaf\:surname
usaaAccount\:checking -> commonplace\:syrislove : fibo-fbc-pas-caa\:AccountHolder
commonplace\:eristocrates -> Collier^^xsd\:string : foaf\:lastName
commonplace\:eristocrates -> foaf\:Person : rdf\:type
usaaAccount\:platinumVisa -> commonplace\:syrislove : fibo-fbc-pas-caa\:AccountHolder
wellsFargoAccount\:installmentLoans -> commonplace\:eristocrates : fibo-fbc-pas-caa\:AccountHolder
commonplace\:eristocrates -> commonplace\:syrislove : foaf\:knows
wellsFargoAccount\:installmentLoans -> fibo-loan-ln-ln\:LoanSpecificCustomerAccount : rdf\:type
commonplace\:eristocrates -> https\://cms.leoncountyfl.gov/Government/Departments/Information-and-Technology/Office-of-Information-Technology^^xsd\:anyURI : foaf\:workplaceHomepage
commonplace\:syrislove -> Fisher^^xsd\:string : foaf\:lastName
commonplace\:syrislove -> syrislove^^xsd\:string : foaf\:nick