module DoxAletheia.Rdf_Distribution.Single



let manual_distributions =
    [|



       "https://www.omg.org/spec/Commons/AnnotationVocabulary/", "https://www.omg.org/spec/Commons/AnnotationVocabulary.ttl"
       "https://www.omg.org/spec/Commons/BusinessAuthorizations/", "https://www.omg.org/spec/Commons/BusinessAuthorizations.ttl"
       "https://www.omg.org/spec/Commons/Classifiers/", "https://www.omg.org/spec/Commons/Classifiers.ttl"
       "https://www.omg.org/spec/Commons/CodesAndCodeSets/", "https://www.omg.org/spec/Commons/CodesAndCodeSets.ttl"
       "https://www.omg.org/spec/Commons/Collections/", "https://www.omg.org/spec/Commons/Collections.ttl"
       "https://www.omg.org/spec/Commons/ContextualDesignators/", "https://www.omg.org/spec/Commons/ContextualDesignators.ttl"
       "https://www.omg.org/spec/Commons/ContextualIdentifiers/", "https://www.omg.org/spec/Commons/ContextualIdentifiers.ttl"
       "https://www.omg.org/spec/Commons/DatesAndTimes/", "https://www.omg.org/spec/Commons/DatesAndTimes.ttl"
       "https://www.omg.org/spec/Commons/Designators/", "https://www.omg.org/spec/Commons/Designators.ttl"
       "https://www.omg.org/spec/Commons/Documents/", "https://www.omg.org/spec/Commons/Documents.ttl"
       "https://www.omg.org/spec/Commons/Identifiers/", "https://www.omg.org/spec/Commons/Identifiers.ttl"
       "https://www.omg.org/spec/Commons/Locations/", "https://www.omg.org/spec/Commons/Locations.ttl"
       "https://www.omg.org/spec/Commons/Organizations/", "https://www.omg.org/spec/Commons/Organizations.ttl"
       "https://www.omg.org/spec/Commons/PartiesAndSituations/", "https://www.omg.org/spec/Commons/PartiesAndSituations.ttl"
       "https://www.omg.org/spec/Commons/QuantitiesAndUnits/", "https://www.omg.org/spec/Commons/QuantitiesAndUnits.ttl"
       "https://www.omg.org/spec/Commons/RegistrationAuthorities/", "https://www.omg.org/spec/Commons/RegistrationAuthorities.ttl"
       "https://www.omg.org/spec/Commons/RegulatoryAgencies/", "https://www.omg.org/spec/Commons/RegulatoryAgencies.ttl"
       "https://www.omg.org/spec/Commons/RolesAndCompositions/", "https://www.omg.org/spec/Commons/RolesAndCompositions.ttl"
       "https://www.omg.org/spec/Commons/SitesAndFacilities/", "https://www.omg.org/spec/Commons/SitesAndFacilities.ttl"
       "https://www.omg.org/spec/Commons/TextDatatype/", "https://www.omg.org/spec/Commons/TextDatatype.ttl"
       "https://www.omg.org/spec/LCC/Countries/CountryRepresentation/", "https://www.omg.org/spec/LCC/Countries/CountryRepresentation.ttl"
       "https://www.omg.org/spec/LCC/Countries/ISO3166-1-CountryCodes/", "https://www.omg.org/spec/LCC/Countries/ISO3166-1-CountryCodes.ttl"
       "https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-CA/", "https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-CA.ttl"
       "https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-GB/", "https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-GB.ttl"
       "https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-MX/", "https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-MX.ttl"
       "https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-US/", "https://www.omg.org/spec/LCC/Countries/Regions/ISO3166-2-SubdivisionCodes-US.ttl"
       "https://www.gleif.org/ontology/L1/", "https://www.gleif.org/ontology/pylodev2/data_file.ttl"
       "http://purl.org/HDT/hdt#", "https://www.w3.org/submissions/2011/SUBM-HDT-RDFS-20110330/HDT.rdf"
       "http://kaiko.getalp.org/dbnary#", "https://kaiko.getalp.org/static/datamodel/2.1.2/ontology.ttl"
       "http://www.w3.org/2011/http-headers#", "https://www.w3.org/2011/http-headers.rdf"
       "http://www.w3.org/2011/http-methods#", "http://www.w3.org/2011/http-methods.rdf"
       "http://www.w3.org/2011/http-statusCodes#", "http://www.w3.org/2011/http-statusCodes.rdf"
       "https://www.w3.org/ns/posix/stat#", "https://www.w3.org/ns/posix/stat.rdf"
       "http://www.w3.org/2001/XMLSchema#", "https://raw.githubusercontent.com/ruby-rdf/rdf/refs/heads/develop/etc/xsd.ttl"
       "https://www.w3.org/ns/activitystreams#", "https://www.w3.org/ns/activitystreams-owl"
       "http://www.w3.org/ns/json-ld#", "https://www.w3.org/ns/json-ld.jsonld"
       "http://www.w3.org/2007/05/powder#", "https://www.w3.org/TR/2007/WD-powder-voc-20070925/wdr.rdf"
       // "http://www.w3.org/2002/12/cal/icaltzd#", "https://www.w3.org/2002/12/cal/icaltzd.rdf"
       "https://schema.org/", "https://schema.org/version/latest/schemaorg-current-https.ttl"
       "https://termlex.oeg.fi.upm.es/termlex#", "https://termlex.oeg.fi.upm.es/static/termlex.rdf"
       "https://w3id.org/function/ontology#", "https://fno.io/ontology/ontology.ttl"
       "https://w3id.org/function/vocabulary/mapping#", "https://fno.io/vocabulary/mapping/0.2.1/ontology.ttl"
       "https://w3id.org/function/vocabulary/implementation#", "https://fno.io/vocabulary/implementation/0.1.1/ontology.ttl"
       "https://w3id.org/function/vocabulary/composition#", "https://fno.io/vocabulary/composition/0.1.0/ontology.ttl"
       "http://www.w3.org/ns/shacl-shacl#", "https://www.w3.org/ns/shacl-shacl.ttl"
       "http://www.w3.org/ns/shex#", "https://www.w3.org/ns/shex.ttl"
       "http://aims.fao.org/aos/agrontology#", "http://aims.fao.org/aos/agrontology" // "agrontology"
       "http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#", "http://www.semanticdesktop.org/ontologies/2007/03/22/nmo/nmo.trig" // "nepomuk.nmo.v1"
       "http://www.semanticdesktop.org/ontologies/2007/05/10/nexif#", "http://www.semanticdesktop.org/ontologies/2007/05/10/nexif/nexif.trig" // "nepomuk.nexif.v1"
       "http://www.semanticdesktop.org/ontologies/2007/05/10/nid3#", "http://www.semanticdesktop.org/ontologies/2007/05/10/nid3/nid3.trig" // "nepomuk.nid3.v1"
       "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#", "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo/pimo.trig" // "nepomuk.pimo.v1"
       "http://www.semanticdesktop.org/ontologies/2008/05/20/tmo#", "http://www.semanticdesktop.org/ontologies/2008/05/20/tmo/v1.1/tmo.trig" // "nepomuk.tmo.v1"
       "http://tracker.api.gnome.org/ontology/v3/nrl#", "https://github.com/GNOME/tinysparql/raw/refs/heads/main/src/ontologies/12-nrl.ontology"
       "http://tracker.api.gnome.org/ontology/v3/nie#", "https://github.com/GNOME/tinysparql/raw/refs/heads/main/src/ontologies/nepomuk/30-nie.ontology"
       "http://tracker.api.gnome.org/ontology/v3/nao#", "https://github.com/GNOME/tinysparql/raw/refs/heads/main/src/ontologies/nepomuk/31-nao.ontology"
       "http://tracker.api.gnome.org/ontology/v3/nco#", "https://github.com/GNOME/tinysparql/raw/refs/heads/main/src/ontologies/nepomuk/32-nco.ontology"
       "http://tracker.api.gnome.org/ontology/v3/nfo#", "https://github.com/GNOME/tinysparql/raw/refs/heads/main/src/ontologies/nepomuk/33-nfo.ontology"
       "http://tracker.api.gnome.org/ontology/v3/nmm#", "https://github.com/GNOME/tinysparql/raw/refs/heads/main/src/ontologies/nepomuk/38-nmm.ontology"
       "http://tracker.api.gnome.org/ontology/v3/mfo#", "https://github.com/GNOME/tinysparql/raw/refs/heads/main/src/ontologies/nepomuk/41-mfo.ontology"
       "http://tracker.api.gnome.org/ontology/v3/tracker#", "https://github.com/GNOME/tinysparql/raw/refs/heads/main/src/ontologies/nepomuk/90-tracker.ontology"
       "http://tracker.api.gnome.org/ontology/v3/slo#", "https://github.com/GNOME/tinysparql/raw/refs/heads/main/src/ontologies/nepomuk/92-slo.ontology"
       "http://tracker.api.gnome.org/ontology/v3/osinfo#", "https://github.com/GNOME/tinysparql/raw/refs/heads/main/src/ontologies/nepomuk/93-libosinfo.ontology"
       "http://datashapes.org/dash#", "https://datashapes.org/dash.ttl" // "dash"
       "http://eulersharp.sourceforge.net/2003/03swap/agent#", "http://eulersharp.sourceforge.net/2003/03swap/agent" // "swap.agent"
       "http://eulersharp.sourceforge.net/2003/03swap/bioSKOSSchemes#", "http://eulersharp.sourceforge.net/2003/03swap/bioSKOSSchemes" // "swap.bioSKOSSchemes"
       "http://eulersharp.sourceforge.net/2003/03swap/care#", "http://eulersharp.sourceforge.net/2003/03swap/care" // "swap.care"
       "http://eulersharp.sourceforge.net/2003/03swap/coding#", "http://eulersharp.sourceforge.net/2003/03swap/coding" // "swap.coding"
       "http://eulersharp.sourceforge.net/2003/03swap/computer#", "http://eulersharp.sourceforge.net/2003/03swap/computer" // "swap.computer"
       "http://eulersharp.sourceforge.net/2003/03swap/countries#", "http://eulersharp.sourceforge.net/2003/03swap/countries" // "swap.countries"
       "http://eulersharp.sourceforge.net/2003/03swap/decisionSupport#", "http://eulersharp.sourceforge.net/2003/03swap/decisionSupport" // "swap.decisionSupport"
       "http://eulersharp.sourceforge.net/2003/03swap/digitalProcedure#", "http://eulersharp.sourceforge.net/2003/03swap/digitalProcedure" // "swap.digitalProcedure"
       "http://eulersharp.sourceforge.net/2003/03swap/document#", "http://eulersharp.sourceforge.net/2003/03swap/document" // "swap.document"
       "http://eulersharp.sourceforge.net/2003/03swap/environment#", "http://eulersharp.sourceforge.net/2003/03swap/environment" // "swap.environment"
       "http://eulersharp.sourceforge.net/2003/03swap/event#", "http://eulersharp.sourceforge.net/2003/03swap/event" // "swap.event"
       "http://eulersharp.sourceforge.net/2003/03swap/foster#", "http://eulersharp.sourceforge.net/2003/03swap/foster" // "swap.foster"
       "http://eulersharp.sourceforge.net/2003/03swap/genomeAbnormality#", "http://eulersharp.sourceforge.net/2003/03swap/genomeAbnormality" // "swap.genomeAbnormality"
       "http://eulersharp.sourceforge.net/2003/03swap/human#", "http://eulersharp.sourceforge.net/2003/03swap/human" // "swap.human"
       "http://eulersharp.sourceforge.net/2003/03swap/humanBody#", "http://eulersharp.sourceforge.net/2003/03swap/humanBody" // "swap.humanBody"
       "http://eulersharp.sourceforge.net/2003/03swap/languages#", "http://eulersharp.sourceforge.net/2003/03swap/languages" // "swap.languages"
       "http://eulersharp.sourceforge.net/2003/03swap/organism#", "http://eulersharp.sourceforge.net/2003/03swap/organism" // "swap.organism"
       "http://eulersharp.sourceforge.net/2003/03swap/organization#", "http://eulersharp.sourceforge.net/2003/03swap/organization" // "swap.organization"
       "http://eulersharp.sourceforge.net/2003/03swap/physicalResource#", "http://eulersharp.sourceforge.net/2003/03swap/physicalResource" // "swap.physicalResource"
       "http://eulersharp.sourceforge.net/2003/03swap/quantities#", "http://eulersharp.sourceforge.net/2003/03swap/quantities" // "swap.quantities"
       "http://eulersharp.sourceforge.net/2003/03swap/space#", "http://eulersharp.sourceforge.net/2003/03swap/space" // "swap.space"
       "http://eulersharp.sourceforge.net/2003/03swap/sparql#", "http://eulersharp.sourceforge.net/2003/03swap/sparql" // "swap.sparql"
       "http://eulersharp.sourceforge.net/2003/03swap/sparqlAnalysis#", "http://eulersharp.sourceforge.net/2003/03swap/sparqlAnalysis" // "swap.sparqlAnalysis"
       "http://eulersharp.sourceforge.net/2003/03swap/sparqlAnalysisTemplate#", "http://eulersharp.sourceforge.net/2003/03swap/sparqlAnalysisTemplate" // "swap.sparqlAnalysisTemplate"
       "http://eulersharp.sourceforge.net/2003/03swap/substanceForms#", "http://eulersharp.sourceforge.net/2003/03swap/substanceForms" // "swap.substanceForms"
       "http://eulersharp.sourceforge.net/2003/03swap/time#", "http://eulersharp.sourceforge.net/2003/03swap/time" // "swap.time"
       "http://eulersharp.sourceforge.net/2003/03swap/units#", "http://eulersharp.sourceforge.net/2003/03swap/units" // "swap.units"
       "http://eulersharp.sourceforge.net/2003/03swap/weekScheme#", "http://eulersharp.sourceforge.net/2003/03swap/weekScheme" // "swap.weekScheme"
       "http://eulersharp.sourceforge.net/2003/03swap/workflow#", "http://eulersharp.sourceforge.net/2003/03swap/workflow" // "swap.workflow"
       // "http://example.org/dctap#", "https://github.com/dcmi/dctap/raw/refs/heads/main/dctap.ttl" // "dcmi.dctap"
       "http://id.loc.gov/ontologies/bflc/", "https://id.loc.gov/ontologies/bflc.rdf"
       // "http://id.loc.gov/ontologies/bibframe/", "https://github.com/lcnetdev/bibframe-ontology/raw/refs/heads/main/bibframe.rdf" // "loc.bibframe"
       "http://open-services.net/ns/am#", "https://docs.oasis-open-projects.org/oslc-op/am/v3.0/os/architecture-management-vocab.ttl" // "oasis.oslc.am"
       "http://open-services.net/ns/auto#", "https://docs.oasis-open-projects.org/oslc-op/auto/v2.1/psd01/automation-vocab.ttl" // "oasis.oslc.auto"
       "http://open-services.net/ns/cm#", "https://docs.oasis-open-projects.org/oslc-op/cm/v3.0/errata01/os/change-mgt-vocab.ttl" // "oasis.oslc.cm"
       "http://open-services.net/ns/config#", "https://docs.oasis-open-projects.org/oslc-op/config/v1.1/psd01/config-vocab.ttl" // "oasis.oslc.config"
       "http://open-services.net/ns/core/trs#", "https://docs.oasis-open-projects.org/oslc-op/trs/v3.0/os/trs-vocab.ttl" // "oasis.oslc.trs"
       "http://open-services.net/ns/core/trspatch#", "https://docs.oasis-open-projects.org/oslc-op/trs/v3.0/os/trs-vocab.ttl" // "oasis.oslc.trs.patch"
       "http://open-services.net/ns/qm#", "https://docs.oasis-open-projects.org/oslc-op/qm/v2.1/os/quality-management-vocab.ttl" // "oasis.oslc.qm"
       "http://open-services.net/ns/rm#", "https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/os/requirements-management-vocab.ttl" // "oasis.oslc.rm"
       "http://open-services.net/ns/sysmlv2#", "https://docs.oasis-open-projects.org/oslc-op/sysml/v2.0/psd01/sysml-vocab.ttl" // "oasis.oslc.sysml"
       "http://openprovenance.org/model/opmo#", "https://openprovenance.org/opm/model/opmo-20101012.owl" // "opmo"
       "http://purl.org/ontology/olo/core#", "https://github.com/smiy/orderedlistonto/raw/refs/heads/master/rdf/orderedlistontology.n3" // "olo"
       "http://purl.org/spar/bido/", "http://purl.org/spar/bido.ttl" // "spar.bido"
       "http://purl.org/spar/fivestars/", "http://purl.org/spar/fivestars.ttl" // "spar.fivestars"
       "http://purl.org/spar/fr/", "http://purl.org/spar/fr.ttl" // "spar.fr"
       "http://purl.org/spar/frbr/", "http://purl.org/spar/frbr.ttl" // "spar.frbr"
       "http://purl.org/spar/mito/", "http://purl.org/spar/mito.ttl" // "spar.mito"
       "http://purl.org/cerif/frapo/", "http://purl.org/spar/frapo.ttl" // "spar.frapo"
       "http://www.daml.org/services/owl-s/1.2/ActorDefault.owl#", "http://www.daml.org/services/owl-s/1.2/ActorDefault.owl" // "owl_s.ActorDefault"
       "http://www.daml.org/services/owl-s/1.2/generic/Expression.owl#", "http://www.daml.org/services/owl-s/1.2/generic/Expression.owl" // "owl_s.Expression"
       "http://www.daml.org/services/owl-s/1.2/generic/ObjectList.owl#", "http://www.daml.org/services/owl-s/1.2/generic/ObjectList.owl" // "owl_s.ObjectList"
       "http://www.daml.org/services/owl-s/1.2/Grounding.owl#", "http://www.daml.org/services/owl-s/1.2/Grounding.owl" // "owl_s.Grounding"
       "http://www.daml.org/services/owl-s/1.2/GroundingDeprecatedElements.owl", "http://www.daml.org/services/owl-s/1.2/GroundingDeprecatedElements.owl" // "owl_s.GroundingDeprecatedElements"
       "http://www.daml.org/services/owl-s/1.2/Process.owl", "http://www.daml.org/services/owl-s/1.2/ProcessDeprecatedElements.owl" // "owl_s.ProcessDeprecatedElements"
       "http://www.daml.org/services/owl-s/1.2/Process.owl#", "http://www.daml.org/services/owl-s/1.2/Process.owl" // "owl_s.Process"
       "http://www.daml.org/services/owl-s/1.2/Profile.owl#", "http://www.daml.org/services/owl-s/1.2/Profile.owl" // "owl_s.Profile"
       "http://www.daml.org/services/owl-s/1.2/ProfileAdditionalParameters.owl#", "http://www.daml.org/services/owl-s/1.2/ProfileAdditionalParameters.owl" // "owl_s.Profile.AdditionalParameters"
       "http://www.daml.org/services/owl-s/1.2/Resource.owl#", "http://www.daml.org/services/owl-s/1.2/Resource.owl" // "owl_s.Resource"
       "http://www.daml.org/services/owl-s/1.2/Service.owl#", "https://www.daml.org/services/owl-s/1.2/Service.owl" // "owl_s.Service"
       "http://www.loa-cnr.it/ontologies/DOLCE-Lite.owl#", "https://github.com/iddi/sofia/raw/refs/heads/master/eu.sofia.adk.common/ontologies/foundational/DOLCE-Lite.owl" // "dolce.lite"
       "http://www.loc.gov/premis/rdf/v3/", "https://github.com/lcnetdev/PREMIS/raw/refs/heads/master/premis3.owl" // "loc.premis"
       "http://www.lexinfo.net/ontology/3.0/lexinfo#", "http://www.lexinfo.net/ontology/3.0/lexinfo.ttl" // "ontolex.lexinfo"
       "http://www.w3.org/2000/10/swap/crypto#", "http://www.w3.org/2000/10/swap/crypto" // "swap.crypto"
       "http://www.w3.org/2000/10/swap/grammar/bnf#", "http://www.w3.org/2000/10/swap/grammar/bnf" // "swap.grammar.bnf"
       "http://www.w3.org/2000/10/swap/list#", "http://www.w3.org/2000/10/swap/list" // "swap.list"
       "http://www.w3.org/2000/10/swap/math#", "http://www.w3.org/2000/10/swap/math" // "swap.math"
       "http://www.w3.org/2000/10/swap/os#", "http://www.w3.org/2000/10/swap/os" // "swap.os"
       "http://www.w3.org/2000/10/swap/pim/doc#", "http://www.w3.org/2000/10/swap/pim/doc" // "swap.pim.doc"
       "http://www.w3.org/2000/10/swap/pim/email#", "http://www.w3.org/2000/10/swap/pim/email" // "swap.pim.email"
       "http://www.w3.org/2000/10/swap/pim/ical#", "http://www.w3.org/2000/10/swap/pim/ical" // "swap.pim.ical"
       "http://www.w3.org/2000/10/swap/pim/qif#", "http://www.w3.org/2000/10/swap/pim/qif" // "swap.pim.qif"
       "http://www.w3.org/2000/10/swap/pim/travelFig#", "http://www.w3.org/2000/10/swap/pim/travelFig" // "swap.pim.travelFig"
       "http://www.w3.org/2000/10/swap/pim/travelTerms#", "http://www.w3.org/2000/10/swap/pim/travelTerms" // "swap.pim.travelTerms"
       "http://www.w3.org/2000/10/swap/pim/usps#", "http://www.w3.org/2000/10/swap/pim/usps" // "swap.pim.usps"
       "http://www.w3.org/2000/10/swap/reason#", "http://www.w3.org/2000/10/swap/reason" // "swap.reason"
       "http://www.w3.org/2000/10/swap/set#", "http://www.w3.org/2000/10/swap/set" // "swap.set"
       "http://www.w3.org/2000/10/swap/string#", "http://www.w3.org/2000/10/swap/string" // "swap.string"
       "http://www.w3.org/2004/06/rei#", "http://www.w3.org/2004/06/rei#" // "rei"
       "http://www.w3.org/ns/solid/acp#", "http://www.w3.org/ns/solid/acp#" // "acp"
       "http://www.w3.org/ns/solid/interop#", "http://www.w3.org/ns/solid/interop#" // "interop"
       "http://www.w3.org/ns/solid/notifications#", "http://www.w3.org/ns/solid/notifications#" // "notify"
       "http://www.w3.org/ns/solid/oidc#", "http://www.w3.org/ns/solid/oidc#" // "oidc"
       "http://www.w3.org/ns/spec#", "http://www.w3.org/ns/spec#" // "spec"
       "https://globalwordnet.github.io/schemas/wn#", "https://www.w3.org/2006/03/wn/wn20/schemas/wnfull.rdfs" // "wordnet.wn"
       "https://ns.dublincore.org/openwemi/", "https://dcmi.github.io/openwemi/ns/openWEMI.ttl" // "dcmi.openwemi"
       // "https://purl.org/heals/eo#", "https://raw.githubusercontent.com/tetherless-world/explanation-ontology/master/Ontologies/v2/explanation-ontology.owl" // "eo"
       "https://spdx.org/rdf/3.1/terms/", "https://spdx.github.io/spdx-spec/3.1-RC1/rdf/spdx-model.ttl" // "spdx3"
       "http://www.loa-cnr.it/ontologies/ExtendedDnS.owl#", "https://github.com/iddi/sofia/raw/refs/heads/master/eu.sofia.adk.common/ontologies/foundational/ExtendedDnS.owl" // "dns"
       // "http://www.opengis.net/ont/geosparql#", "http://www.opengis.net/ont/geosparql#" // "opengis.geosparql"
       "http://www.opengis.net/ont/sf#", "http://www.opengis.net/ont/sf#" // "opengis.sf"
       "http://www.essepuntato.it/2008/12/pattern#", "https://sourceforge.net/p/dwellonit/code/HEAD/tree/StructuralPattern/pattern.owl?format=raw" // "dwellonit.pattern"
       // "http://www.essepuntato.it/2011/02/argumentmodel/", "https://sourceforge.net/p/dwellonit/code/HEAD/tree/ArgumentModel/argumentmodel.owl?format=raw" // "dwellonit.arg"
       "http://www.essepuntato.it/2012/04/tvc/", "https://sourceforge.net/p/dwellonit/code/HEAD/tree/TimeIndexedValueInContext/tvc.owl?format=raw" // "dwellonit.tvc"
       "http://www.essepuntato.it/2013/10/vagueness/", "https://sourceforge.net/p/dwellonit/code/HEAD/tree/VaguenessOntology/model.owl?format=raw" // "dwellonit.vag"
       "http://qudt.org/vocab/constant/", "http://qudt.org/3.1.10/vocab/constant" // "qudt-constant"
       "http://qudt.org/vocab/dimensionvector", "http://qudt.org/3.1.10/vocab/dimensionvector" // "qudt-dimensionvector"
       "http://qudt.org/vocab/quantitykind", "http://qudt.org/3.1.10/vocab/quantitykind" // "qudt-quantitykind"
       "http://qudt.org/vocab/soqk", "http://qudt.org/3.1.10/vocab/soqk" // "qudt-system-quantitykind"
       "http://purl.org/swan/2.0/", "https://rawcdn.githack.com/pav-ontology/swan-ontology/2.0.1/swan.owl" // "swan"
       "http://purl.org/swan/2.0/collections/", "https://rawcdn.githack.com/pav-ontology/swan-ontology/2.0.1/collections.owl" // "swan.collections"
       "http://purl.org/swan/2.0/discourse-elements/", "https://rawcdn.githack.com/pav-ontology/swan-ontology/2.0.1/discourse-elements.owl" // "swan.discourse.elements"
       "http://purl.org/swan/2.0/discourse-relationships/", "https://rawcdn.githack.com/pav-ontology/swan-ontology/2.0.1/discourse-relationships.owl" // "swan.discourse.relationships"
       "http://purl.org/swan/2.0/experiment", "https://rawcdn.githack.com/pav-ontology/swan-ontology/2.0.1/experiments.owl" // "swan.experiments"
       "http://purl.org/dcx/lrmi-terms/", "http://dublincore.org/specifications/lrmi/lrmi_terms/2022-06-14/lrmi-terms.ttl" // "dcmi.lrmi"
       "http://purl.org/dcx/lrmi-vocabs/alignmentType/", "http://dublincore.org/vocabs/alignmentType.ttl" // "dcmi.lrmi.alignment"
       "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/", "http://dublincore.org/vocabs/educationalAudienceRole.ttl" // "dcmi.lrmi.audRole"
       "http://purl.org/dcx/lrmi-vocabs/educationalUse/", "	http://dublincore.org/vocabs/educationalUse.ttl" // "dcmi.lrmi.edUse"
       "http://purl.org/dcx/lrmi-vocabs/interactivityType/", "http://dublincore.org/vocabs/interactivityType.ttl" // "dcmi.lrmi.interact"
       "http://purl.org/dcx/lrmi-vocabs/learningResourceType/", "https://www.dublincore.org/vocabs/learningResourceType.ttl" // "dcmi.lrmi.resourceType"
       "http://www.w3.org/2006/03/wn/wn20/schema/", "https://www.w3.org/2006/03/wn/wn20/schemas/wnfull.rdfs"
       "https://www.commoncoreontologies.org/", "https://github.com/CommonCoreOntology/CommonCoreOntologies/raw/refs/heads/develop/src/cco-merged/CommonCoreOntologiesMerged.ttl"
       "https://www.commoncoreontologies.org/BarcodeOntology/", "https://github.com/CommonCoreOntology/CommonCoreOntologies/raw/refs/heads/develop/src/cco-extensions/BarcodeOntology.ttl"
       "https://www.commoncoreontologies.org/FamilialRelationsOntology", "https://github.com/CommonCoreOntology/CommonCoreOntologies/raw/refs/heads/develop/src/cco-extensions/FamilialRelationsOntology.ttl"
       // "https://www.commoncoreontologies.org/mro/", "https://github.com/CommonCoreOntology/CommonCoreOntologies/raw/refs/heads/develop/src/cco-extensions/ModalRelationOntology.ttl" // "cco.mro"
       "https://open-metadata.org/ontology/", "https://github.com/open-metadata/OpenMetadataStandards/raw/refs/heads/main/rdf/ontology/openmetadata.ttl"



       |]
