sanctuary\:siamesederp -> foaf\:Person : rdf\:type
sanctuary\:eristocrates -> foaf\:Person : rdf\:type
sanctuary\:yaladre -> commonplace\:Quest_of_D : foaf\:topic_interest
sanctuary\:yaladre -> foaf\:Person : rdf\:type
sanctuary\:regen -> foaf\:Person : rdf\:type
sanctuary\:yaladre -> commonplace\:Gitadora : foaf\:topic_interest