graph LR
  0["sanctuary:siamesederp"]
  1["foaf:Person"]
  2["sanctuary:eristocrates"]
  3["sanctuary:yaladre"]
  4["commonplace:Quest_of_D"]
  5["sanctuary:regen"]
  6["commonplace:Gitadora"]
  0 -->|"rdf:type"| 1
  2 -->|"rdf:type"| 1
  3 -->|"rdf:type"| 1
  3 -->|"foaf:topic_interest"| 4
  3 -->|"foaf:topic_interest"| 6
  5 -->|"rdf:type"| 1
