open System.IO

#load "UserPersistence.fsx"
#load "RecordPortGenerator.fsx"

open UserPersistence

module stem =
    let name = "UserPersistence"
    let fsx = $"{name}.fsx"

    module generated =
        let fsx = $"{name}.Generated.fsx"

let parent_directory_path = __SOURCE_DIRECTORY__


let codegen =
    $""" 
// <auto-generated>
// Generated from runtime F# reflection.
// Do not edit by hand.

#load @"{Path.Combine(parent_directory_path, stem.fsx)}"
open {stem.name}
{RecordPortGenerator.writeInterfaceFor<UserPersistence> $"{stem.generated.fsx}"}
"""

printfn "%s" codegen


File.WriteAllText(Path.Combine(parent_directory_path, stem.generated.fsx), codegen)
