namespace Xml.spec.Namespace

module xml'spec =
    let _prefixID =
        Communication.Internet.Standard.Resource.Identifier.Internationalized.inhabitant
            "https://www.w3.org/TR/xml/#"
            None
            (Some "xml.spec")
            None

    let ABK = { _prefixID with _localName = "ABK" }
    let ABKDW = { _prefixID with _localName = "ABKDW" }
    let AVNormalize = { _prefixID with _localName = "AVNormalize" }
    let Aho = { _prefixID with _localName = "Aho" }
    let CHARACTERS = { _prefixID with _localName = "CHARACTERS" }
    let CharClasses = { _prefixID with _localName = "CharClasses" }
    let Clark = { _prefixID with _localName = "Clark" }
    let CleanAttrVals = { _prefixID with _localName = "CleanAttrVals" }
    let Copyright = { _prefixID with _localName = "Copyright" }
    let E09 = { _prefixID with _localName = "E09" }
    let EDUnique = { _prefixID with _localName = "EDUnique" }
    let ExtSubset = { _prefixID with _localName = "ExtSubset" }
    let FixedAttr = { _prefixID with _localName = "FixedAttr" }
    let GIMatch = { _prefixID with _localName = "GIMatch" }
    let IANA = { _prefixID with _localName = "IANA" }
    let ``IANA-LANGCODES`` = { _prefixID with _localName = "IANA-LANGCODES" }
    let ISO10646 = { _prefixID with _localName = "ISO10646" }
    let ``ISO10646-2000`` = { _prefixID with _localName = "ISO10646-2000" }
    let ISO10744 = { _prefixID with _localName = "ISO10744" }
    let ISO3166 = { _prefixID with _localName = "ISO3166" }
    let ISO639 = { _prefixID with _localName = "ISO639" }
    let ISO8879 = { _prefixID with _localName = "ISO8879" }
    let Legal_Disclaimer = { _prefixID with _localName = "Legal_Disclaimer" }
    let ``NT-AttDef`` = { _prefixID with _localName = "NT-AttDef" }
    let ``NT-AttType`` = { _prefixID with _localName = "NT-AttType" }
    let ``NT-AttValue`` = { _prefixID with _localName = "NT-AttValue" }
    let ``NT-AttlistDecl`` = { _prefixID with _localName = "NT-AttlistDecl" }
    let ``NT-Attribute`` = { _prefixID with _localName = "NT-Attribute" }
    let ``NT-BaseChar`` = { _prefixID with _localName = "NT-BaseChar" }
    let ``NT-CDEnd`` = { _prefixID with _localName = "NT-CDEnd" }
    let ``NT-CDSect`` = { _prefixID with _localName = "NT-CDSect" }
    let ``NT-CDStart`` = { _prefixID with _localName = "NT-CDStart" }
    let ``NT-CData`` = { _prefixID with _localName = "NT-CData" }
    let ``NT-Char`` = { _prefixID with _localName = "NT-Char" }
    let ``NT-CharData`` = { _prefixID with _localName = "NT-CharData" }
    let ``NT-CharRef`` = { _prefixID with _localName = "NT-CharRef" }
    let ``NT-CombiningChar`` = { _prefixID with _localName = "NT-CombiningChar" }
    let ``NT-Comment`` = { _prefixID with _localName = "NT-Comment" }
    let ``NT-DeclSep`` = { _prefixID with _localName = "NT-DeclSep" }
    let ``NT-DefaultDecl`` = { _prefixID with _localName = "NT-DefaultDecl" }
    let ``NT-Digit`` = { _prefixID with _localName = "NT-Digit" }
    let ``NT-ETag`` = { _prefixID with _localName = "NT-ETag" }
    let ``NT-EmptyElemTag`` = { _prefixID with _localName = "NT-EmptyElemTag" }
    let ``NT-EncName`` = { _prefixID with _localName = "NT-EncName" }
    let ``NT-EncodingDecl`` = { _prefixID with _localName = "NT-EncodingDecl" }
    let ``NT-EntityDecl`` = { _prefixID with _localName = "NT-EntityDecl" }
    let ``NT-EntityDef`` = { _prefixID with _localName = "NT-EntityDef" }
    let ``NT-EntityRef`` = { _prefixID with _localName = "NT-EntityRef" }
    let ``NT-EntityValue`` = { _prefixID with _localName = "NT-EntityValue" }
    let ``NT-EnumeratedType`` = { _prefixID with _localName = "NT-EnumeratedType" }
    let ``NT-Enumeration`` = { _prefixID with _localName = "NT-Enumeration" }
    let ``NT-Eq`` = { _prefixID with _localName = "NT-Eq" }
    let ``NT-Extender`` = { _prefixID with _localName = "NT-Extender" }
    let ``NT-ExternalID`` = { _prefixID with _localName = "NT-ExternalID" }
    let ``NT-GEDecl`` = { _prefixID with _localName = "NT-GEDecl" }
    let ``NT-Ideographic`` = { _prefixID with _localName = "NT-Ideographic" }
    let ``NT-Ignore`` = { _prefixID with _localName = "NT-Ignore" }
    let ``NT-Letter`` = { _prefixID with _localName = "NT-Letter" }
    let ``NT-Misc`` = { _prefixID with _localName = "NT-Misc" }
    let ``NT-Mixed`` = { _prefixID with _localName = "NT-Mixed" }
    let ``NT-NDataDecl`` = { _prefixID with _localName = "NT-NDataDecl" }
    let ``NT-Name`` = { _prefixID with _localName = "NT-Name" }
    let ``NT-NameChar`` = { _prefixID with _localName = "NT-NameChar" }
    let ``NT-NameStartChar`` = { _prefixID with _localName = "NT-NameStartChar" }
    let ``NT-Names`` = { _prefixID with _localName = "NT-Names" }
    let ``NT-Nmtoken`` = { _prefixID with _localName = "NT-Nmtoken" }
    let ``NT-Nmtokens`` = { _prefixID with _localName = "NT-Nmtokens" }
    let ``NT-NotationDecl`` = { _prefixID with _localName = "NT-NotationDecl" }
    let ``NT-NotationType`` = { _prefixID with _localName = "NT-NotationType" }
    let ``NT-PEDecl`` = { _prefixID with _localName = "NT-PEDecl" }
    let ``NT-PEDef`` = { _prefixID with _localName = "NT-PEDef" }
    let ``NT-PEReference`` = { _prefixID with _localName = "NT-PEReference" }
    let ``NT-PI`` = { _prefixID with _localName = "NT-PI" }
    let ``NT-PITarget`` = { _prefixID with _localName = "NT-PITarget" }
    let ``NT-PubidChar`` = { _prefixID with _localName = "NT-PubidChar" }
    let ``NT-PubidLiteral`` = { _prefixID with _localName = "NT-PubidLiteral" }
    let ``NT-PublicID`` = { _prefixID with _localName = "NT-PublicID" }
    let ``NT-Reference`` = { _prefixID with _localName = "NT-Reference" }
    let ``NT-S`` = { _prefixID with _localName = "NT-S" }
    let ``NT-SDDecl`` = { _prefixID with _localName = "NT-SDDecl" }
    let ``NT-STag`` = { _prefixID with _localName = "NT-STag" }
    let ``NT-StringType`` = { _prefixID with _localName = "NT-StringType" }
    let ``NT-SystemLiteral`` = { _prefixID with _localName = "NT-SystemLiteral" }
    let ``NT-TextDecl`` = { _prefixID with _localName = "NT-TextDecl" }
    let ``NT-TokenizedType`` = { _prefixID with _localName = "NT-TokenizedType" }
    let ``NT-VersionInfo`` = { _prefixID with _localName = "NT-VersionInfo" }
    let ``NT-VersionNum`` = { _prefixID with _localName = "NT-VersionNum" }
    let ``NT-XMLDecl`` = { _prefixID with _localName = "NT-XMLDecl" }
    let ``NT-children`` = { _prefixID with _localName = "NT-children" }
    let ``NT-choice`` = { _prefixID with _localName = "NT-choice" }
    let ``NT-conditionalSect`` = { _prefixID with _localName = "NT-conditionalSect" }
    let ``NT-content`` = { _prefixID with _localName = "NT-content" }
    let ``NT-contentspec`` = { _prefixID with _localName = "NT-contentspec" }
    let ``NT-cp`` = { _prefixID with _localName = "NT-cp" }
    let ``NT-doctypedecl`` = { _prefixID with _localName = "NT-doctypedecl" }
    let ``NT-document`` = { _prefixID with _localName = "NT-document" }
    let ``NT-element`` = { _prefixID with _localName = "NT-element" }
    let ``NT-elementdecl`` = { _prefixID with _localName = "NT-elementdecl" }
    let ``NT-extParsedEnt`` = { _prefixID with _localName = "NT-extParsedEnt" }
    let ``NT-extSubset`` = { _prefixID with _localName = "NT-extSubset" }
    let ``NT-extSubsetDecl`` = { _prefixID with _localName = "NT-extSubsetDecl" }
    let ``NT-ignoreSect`` = { _prefixID with _localName = "NT-ignoreSect" }

    let ``NT-ignoreSectContents`` =
        { _prefixID with _localName = "NT-ignoreSectContents" }

    let ``NT-includeSect`` = { _prefixID with _localName = "NT-includeSect" }
    let ``NT-intSubset`` = { _prefixID with _localName = "NT-intSubset" }
    let ``NT-markupdecl`` = { _prefixID with _localName = "NT-markupdecl" }
    let ``NT-prolog`` = { _prefixID with _localName = "NT-prolog" }
    let ``NT-seq`` = { _prefixID with _localName = "NT-seq" }
    let NoDuplicateTokens = { _prefixID with _localName = "NoDuplicateTokens" }
    let NoExternalRefs = { _prefixID with _localName = "NoExternalRefs" }
    let NoNotationEmpty = { _prefixID with _localName = "NoNotationEmpty" }
    let Notations = { _prefixID with _localName = "Notations" }
    let OneNotationPer = { _prefixID with _localName = "OneNotationPer" }
    let ``PE-between-Decls`` = { _prefixID with _localName = "PE-between-Decls" }
    let RFC1766 = { _prefixID with _localName = "RFC1766" }
    let RFC2141 = { _prefixID with _localName = "RFC2141" }
    let RequiredAttr = { _prefixID with _localName = "RequiredAttr" }
    let TextEntities = { _prefixID with _localName = "TextEntities" }
    let Unicode = { _prefixID with _localName = "Unicode" }
    let UniqueNotationName = { _prefixID with _localName = "UniqueNotationName" }
    let ValueType = { _prefixID with _localName = "ValueType" }
    let W3C_Trademarks = { _prefixID with _localName = "W3C_Trademarks" }
    let ``abstract`` = { _prefixID with _localName = "abstract" }
    let appendices = { _prefixID with _localName = "appendices" }
    let ``as-PE`` = { _prefixID with _localName = "as-PE" }
    let attdecls = { _prefixID with _localName = "attdecls" }
    let bypass = { _prefixID with _localName = "bypass" }
    let char32 = { _prefixID with _localName = "char32" }
    let charencoding = { _prefixID with _localName = "charencoding" }
    let charsets = { _prefixID with _localName = "charsets" }
    let ``condsec-nesting`` = { _prefixID with _localName = "condsec-nesting" }
    let contents = { _prefixID with _localName = "contents" }
    let d0e1106 = { _prefixID with _localName = "d0e1106" }
    let d0e1149 = { _prefixID with _localName = "d0e1149" }
    let d0e1188 = { _prefixID with _localName = "d0e1188" }
    let d0e1271 = { _prefixID with _localName = "d0e1271" }
    let d0e2130 = { _prefixID with _localName = "d0e2130" }
    let d0e2259 = { _prefixID with _localName = "d0e2259" }
    let d0e2403 = { _prefixID with _localName = "d0e2403" }
    let d0e2433 = { _prefixID with _localName = "d0e2433" }
    let d0e2480 = { _prefixID with _localName = "d0e2480" }
    let d0e2553 = { _prefixID with _localName = "d0e2553" }
    let d0e2638 = { _prefixID with _localName = "d0e2638" }
    let d0e2826 = { _prefixID with _localName = "d0e2826" }
    let d0e2926 = { _prefixID with _localName = "d0e2926" }
    let d0e3004 = { _prefixID with _localName = "d0e3004" }
    let d0e3200 = { _prefixID with _localName = "d0e3200" }
    let d0e3369 = { _prefixID with _localName = "d0e3369" }
    let d0e3658 = { _prefixID with _localName = "d0e3658" }
    let d0e3895 = { _prefixID with _localName = "d0e3895" }
    let d0e3966 = { _prefixID with _localName = "d0e3966" }
    let d0e4163 = { _prefixID with _localName = "d0e4163" }
    let d0e4313 = { _prefixID with _localName = "d0e4313" }
    let d0e4481 = { _prefixID with _localName = "d0e4481" }
    let d0e4524 = { _prefixID with _localName = "d0e4524" }
    let d0e4623 = { _prefixID with _localName = "d0e4623" }
    let d0e5457 = { _prefixID with _localName = "d0e5457" }
    let d0e804 = { _prefixID with _localName = "d0e804" }
    let d0e888 = { _prefixID with _localName = "d0e888" }
    let ``def-essential`` = { _prefixID with _localName = "def-essential" }
    let defattrvalid = { _prefixID with _localName = "defattrvalid" }
    let determinism = { _prefixID with _localName = "determinism" }
    let document = { _prefixID with _localName = "document" }
    let ``dt-GERef`` = { _prefixID with _localName = "dt-GERef" }
    let ``dt-PE`` = { _prefixID with _localName = "dt-PE" }
    let ``dt-PERef`` = { _prefixID with _localName = "dt-PERef" }
    let ``dt-app`` = { _prefixID with _localName = "dt-app" }
    let ``dt-attdecl`` = { _prefixID with _localName = "dt-attdecl" }
    let ``dt-attr`` = { _prefixID with _localName = "dt-attr" }
    let ``dt-attrname`` = { _prefixID with _localName = "dt-attrname" }
    let ``dt-attrval`` = { _prefixID with _localName = "dt-attrval" }
    let ``dt-atuseroption`` = { _prefixID with _localName = "dt-atuseroption" }
    let ``dt-cdsection`` = { _prefixID with _localName = "dt-cdsection" }
    let ``dt-character`` = { _prefixID with _localName = "dt-character" }
    let ``dt-chardata`` = { _prefixID with _localName = "dt-chardata" }
    let ``dt-charref`` = { _prefixID with _localName = "dt-charref" }
    let ``dt-comment`` = { _prefixID with _localName = "dt-comment" }
    let ``dt-compat`` = { _prefixID with _localName = "dt-compat" }
    let ``dt-cond-section`` = { _prefixID with _localName = "dt-cond-section" }
    let ``dt-content`` = { _prefixID with _localName = "dt-content" }
    let ``dt-content-model`` = { _prefixID with _localName = "dt-content-model" }
    let ``dt-default`` = { _prefixID with _localName = "dt-default" }
    let ``dt-docent`` = { _prefixID with _localName = "dt-docent" }
    let ``dt-doctype`` = { _prefixID with _localName = "dt-doctype" }
    let ``dt-eetag`` = { _prefixID with _localName = "dt-eetag" }
    let ``dt-eldecl`` = { _prefixID with _localName = "dt-eldecl" }
    let ``dt-elemcontent`` = { _prefixID with _localName = "dt-elemcontent" }
    let ``dt-element`` = { _prefixID with _localName = "dt-element" }
    let ``dt-empty`` = { _prefixID with _localName = "dt-empty" }
    let ``dt-entdecl`` = { _prefixID with _localName = "dt-entdecl" }
    let ``dt-entity`` = { _prefixID with _localName = "dt-entity" }
    let ``dt-entref`` = { _prefixID with _localName = "dt-entref" }
    let ``dt-enumerated`` = { _prefixID with _localName = "dt-enumerated" }
    let ``dt-error`` = { _prefixID with _localName = "dt-error" }
    let ``dt-escape`` = { _prefixID with _localName = "dt-escape" }
    let ``dt-etag`` = { _prefixID with _localName = "dt-etag" }
    let ``dt-extent`` = { _prefixID with _localName = "dt-extent" }
    let ``dt-extlitentval`` = { _prefixID with _localName = "dt-extlitentval" }
    let ``dt-extmkpdecl`` = { _prefixID with _localName = "dt-extmkpdecl" }
    let ``dt-extrepltext`` = { _prefixID with _localName = "dt-extrepltext" }
    let ``dt-fatal`` = { _prefixID with _localName = "dt-fatal" }
    let ``dt-include`` = { _prefixID with _localName = "dt-include" }
    let ``dt-internent`` = { _prefixID with _localName = "dt-internent" }
    let ``dt-interop`` = { _prefixID with _localName = "dt-interop" }
    let ``dt-litentval`` = { _prefixID with _localName = "dt-litentval" }
    let ``dt-markup`` = { _prefixID with _localName = "dt-markup" }
    let ``dt-markupdecl`` = { _prefixID with _localName = "dt-markupdecl" }
    let ``dt-match`` = { _prefixID with _localName = "dt-match" }
    let ``dt-mixed`` = { _prefixID with _localName = "dt-mixed" }
    let ``dt-name`` = { _prefixID with _localName = "dt-name" }
    let ``dt-notation`` = { _prefixID with _localName = "dt-notation" }
    let ``dt-notdecl`` = { _prefixID with _localName = "dt-notdecl" }
    let ``dt-parentchild`` = { _prefixID with _localName = "dt-parentchild" }
    let ``dt-parsedent`` = { _prefixID with _localName = "dt-parsedent" }
    let ``dt-pi`` = { _prefixID with _localName = "dt-pi" }
    let ``dt-pubid`` = { _prefixID with _localName = "dt-pubid" }
    let ``dt-repltext`` = { _prefixID with _localName = "dt-repltext" }
    let ``dt-root`` = { _prefixID with _localName = "dt-root" }
    let ``dt-stag`` = { _prefixID with _localName = "dt-stag" }
    let ``dt-sysid`` = { _prefixID with _localName = "dt-sysid" }
    let ``dt-text`` = { _prefixID with _localName = "dt-text" }
    let ``dt-unparsed`` = { _prefixID with _localName = "dt-unparsed" }
    let ``dt-use-mdecl`` = { _prefixID with _localName = "dt-use-mdecl" }
    let ``dt-valid`` = { _prefixID with _localName = "dt-valid" }
    let ``dt-validating`` = { _prefixID with _localName = "dt-validating" }
    let ``dt-vc`` = { _prefixID with _localName = "dt-vc" }
    let ``dt-wellformed`` = { _prefixID with _localName = "dt-wellformed" }
    let ``dt-wfc`` = { _prefixID with _localName = "dt-wfc" }
    let ``dt-xml-doc`` = { _prefixID with _localName = "dt-xml-doc" }
    let ``dt-xml-proc`` = { _prefixID with _localName = "dt-xml-proc" }
    let ``dt-xmldecl`` = { _prefixID with _localName = "dt-xmldecl" }
    let dtd = { _prefixID with _localName = "dtd" }
    let elemdecls = { _prefixID with _localName = "elemdecls" }
    let elementvalid = { _prefixID with _localName = "elementvalid" }
    let entname = { _prefixID with _localName = "entname" }
    let entproc = { _prefixID with _localName = "entproc" }
    let enum = { _prefixID with _localName = "enum" }
    let error = { _prefixID with _localName = "error" }
    let ``ext-Subset`` = { _prefixID with _localName = "ext-Subset" }
    let forbidden = { _prefixID with _localName = "forbidden" }
    let fulldtd = { _prefixID with _localName = "fulldtd" }
    let ``gen-entity`` = { _prefixID with _localName = "gen-entity" }
    let id = { _prefixID with _localName = "id" }
    let ``id-default`` = { _prefixID with _localName = "id-default" }
    let idref = { _prefixID with _localName = "idref" }
    let ``include-if-valid`` = { _prefixID with _localName = "include-if-valid" }
    let included = { _prefixID with _localName = "included" }
    let indtd = { _prefixID with _localName = "indtd" }
    let inliteral = { _prefixID with _localName = "inliteral" }
    let ``intern-replacement`` = { _prefixID with _localName = "intern-replacement" }
    let nmtok = { _prefixID with _localName = "nmtok" }
    let norecursion = { _prefixID with _localName = "norecursion" }
    let ``not-declared`` = { _prefixID with _localName = "not-declared" }
    let ``not-recognized`` = { _prefixID with _localName = "not-recognized" }
    let notatn = { _prefixID with _localName = "notatn" }
    let ``notice-20130207`` = { _prefixID with _localName = "notice-20130207" }
    let notify = { _prefixID with _localName = "notify" }
    let ``null`` = { _prefixID with _localName = "null" }
    let ``one-id-per-el`` = { _prefixID with _localName = "one-id-per-el" }
    let ``proc-types`` = { _prefixID with _localName = "proc-types" }
    let ``prod-notes`` = { _prefixID with _localName = "prod-notes" }
    let q74 = { _prefixID with _localName = "q74" }
    let rfc2119 = { _prefixID with _localName = "rfc2119" }
    let rfc2376 = { _prefixID with _localName = "rfc2376" }
    let rfc2781 = { _prefixID with _localName = "rfc2781" }
    let rfc3986 = { _prefixID with _localName = "rfc3986" }
    let ``safe-behavior`` = { _prefixID with _localName = "safe-behavior" }
    let ``sec-Disclosure`` = { _prefixID with _localName = "sec-Disclosure" }
    let ``sec-TextDecl`` = { _prefixID with _localName = "sec-TextDecl" }
    let ``sec-attr-defaults`` = { _prefixID with _localName = "sec-attr-defaults" }
    let ``sec-attribute-types`` = { _prefixID with _localName = "sec-attribute-types" }
    let ``sec-bibliography`` = { _prefixID with _localName = "sec-bibliography" }
    let ``sec-cdata-sect`` = { _prefixID with _localName = "sec-cdata-sect" }
    let ``sec-comments`` = { _prefixID with _localName = "sec-comments" }
    let ``sec-common-syn`` = { _prefixID with _localName = "sec-common-syn" }
    let ``sec-condition-sect`` = { _prefixID with _localName = "sec-condition-sect" }
    let ``sec-conformance`` = { _prefixID with _localName = "sec-conformance" }
    let ``sec-core-wg`` = { _prefixID with _localName = "sec-core-wg" }
    let ``sec-doc-entity`` = { _prefixID with _localName = "sec-doc-entity" }
    let ``sec-documents`` = { _prefixID with _localName = "sec-documents" }
    let ``sec-element-content`` = { _prefixID with _localName = "sec-element-content" }
    let ``sec-entexpand`` = { _prefixID with _localName = "sec-entexpand" }
    let ``sec-entity-decl`` = { _prefixID with _localName = "sec-entity-decl" }
    let ``sec-existing-stds`` = { _prefixID with _localName = "sec-existing-stds" }
    let ``sec-external-ent`` = { _prefixID with _localName = "sec-external-ent" }
    let ``sec-guessing`` = { _prefixID with _localName = "sec-guessing" }

    let ``sec-guessing-no-ext-info`` =
        { _prefixID with _localName = "sec-guessing-no-ext-info" }

    let ``sec-guessing-with-ext-info`` =
        { _prefixID with _localName = "sec-guessing-with-ext-info" }

    let ``sec-internal-ent`` = { _prefixID with _localName = "sec-internal-ent" }
    let ``sec-intro`` = { _prefixID with _localName = "sec-intro" }
    let ``sec-lang-tag`` = { _prefixID with _localName = "sec-lang-tag" }
    let ``sec-line-ends`` = { _prefixID with _localName = "sec-line-ends" }
    let ``sec-logical-struct`` = { _prefixID with _localName = "sec-logical-struct" }
    let ``sec-mixed-content`` = { _prefixID with _localName = "sec-mixed-content" }
    let ``sec-notation`` = { _prefixID with _localName = "sec-notation" }
    let ``sec-origin-goals`` = { _prefixID with _localName = "sec-origin-goals" }
    let ``sec-physical-struct`` = { _prefixID with _localName = "sec-physical-struct" }
    let ``sec-pi`` = { _prefixID with _localName = "sec-pi" }
    let ``sec-predefined-ent`` = { _prefixID with _localName = "sec-predefined-ent" }
    let ``sec-prolog-dtd`` = { _prefixID with _localName = "sec-prolog-dtd" }
    let ``sec-references`` = { _prefixID with _localName = "sec-references" }
    let ``sec-rmd`` = { _prefixID with _localName = "sec-rmd" }
    let ``sec-starttags`` = { _prefixID with _localName = "sec-starttags" }
    let ``sec-suggested-names`` = { _prefixID with _localName = "sec-suggested-names" }
    let ``sec-terminology`` = { _prefixID with _localName = "sec-terminology" }
    let ``sec-well-formed`` = { _prefixID with _localName = "sec-well-formed" }
    let ``sec-white-space`` = { _prefixID with _localName = "sec-white-space" }
    let ``sec-xml-and-sgml`` = { _prefixID with _localName = "sec-xml-and-sgml" }
    let ``sec-xml-wg`` = { _prefixID with _localName = "sec-xml-wg" }
    let status = { _prefixID with _localName = "status" }
    let syntax = { _prefixID with _localName = "syntax" }
    let textent = { _prefixID with _localName = "textent" }
    let title = { _prefixID with _localName = "title" }
    let unipart15 = { _prefixID with _localName = "unipart15" }
    let uniqattspec = { _prefixID with _localName = "uniqattspec" }

    let ``vc-MixedChildrenUnique`` =
        { _prefixID with _localName = "vc-MixedChildrenUnique" }

    let ``vc-PEinGroup`` = { _prefixID with _localName = "vc-PEinGroup" }
    let ``vc-PEinMarkupDecl`` = { _prefixID with _localName = "vc-PEinMarkupDecl" }
    let ``vc-check-rmd`` = { _prefixID with _localName = "vc-check-rmd" }
    let ``vc-entdeclared`` = { _prefixID with _localName = "vc-entdeclared" }
    let ``vc-roottype`` = { _prefixID with _localName = "vc-roottype" }
    let ``w3c-doctype`` = { _prefixID with _localName = "w3c-doctype" }
    let websgml = { _prefixID with _localName = "websgml" }
    let ``wf-Legalchar`` = { _prefixID with _localName = "wf-Legalchar" }
    let ``wf-entdeclared`` = { _prefixID with _localName = "wf-entdeclared" }
    let ``wf-entities`` = { _prefixID with _localName = "wf-entities" }

    let ``wfc-PEinInternalSubset`` =
        { _prefixID with _localName = "wfc-PEinInternalSubset" }

    let white = { _prefixID with _localName = "white" }
    let ``xml-names`` = { _prefixID with _localName = "xml-names" }
    let xmldoc = { _prefixID with _localName = "xmldoc" }
