#time on

open System
open System.IO


#load @"C:\Repositories\eristocrates\ipa\Source-code\Host-environment\Common-Language-Runtime\FSharp\Solution\DoxAletheia\Ergonomic_Extensions\ArrayExtensions.fs"
#load @"C:\Repositories\eristocrates\ipa\Source-code\Host-environment\Common-Language-Runtime\FSharp\Solution\DoxAletheia\Ergonomic_Extensions\DiagnosticsErgonomics.fs"
#load @"C:\Repositories\eristocrates\ipa\Source-code\Host-environment\Common-Language-Runtime\FSharp\Solution\DoxAletheia\Ergonomic_Extensions\StringExtensions.fs"
open DoxAletheia
open ArrayExtensions
open DiagnosticsErgonomics
open StringExtensions

let authored_text = 
    $"""
*.pack
Language/Prolog/SWI-Prolog/swipl-9.2.9-1.x64/library/semweb
**/.vs
.fake
secret/
.git/objects/pack/
Application/Microsoft/Edge/data_dir/
Source-code/Host-environment/Common-Language-Runtime/FSharp/Interactive/DoxAletheia/*.nq
Source-code/Host-environment/Common-Language-Runtime/FSharp/Project/MyProvider/packages/
Application/MMT/content/MMT/examples
Source-code/Host-environment/Common-Language-Runtime/FSharp/Interactive/DoxAletheia/Vocabulary/http/www.w3.org/2000/10/swap/pim/contact/hash/con.ttl
    """

let rootDirectory = @"C:\Repositories\eristocrates\ipa"
let gitignoreFilepath = $"""{rootDirectory}\.gitignore"""
// -----------------------------
open System.IO
// https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits


let thresholdBytes = 100L * 1024L * 1024L // 100 MiB

let normalizeToGitPath (p: string) = p.Replace('\\', '/')

let relativeGitPath (rootDir: string) (fullPath: string) =
    Path.GetRelativePath(rootDir, fullPath)
    |> normalizeToGitPath

let escapeGitignoreLine (line: string) =
    // Avoid accidental comment/negation if the path starts with '#' or '!'
    if
        line.StartsWith("#", StringComparison.Ordinal)
        || line.StartsWith("!", StringComparison.Ordinal)
    then
        "\\" + line
    else
        line
















let enumerateFilesRecursive (rootDir: string) : string array =
    let opts = EnumerationOptions()
    opts.RecurseSubdirectories <- true
    opts.IgnoreInaccessible <- true
    opts.AttributesToSkip <- FileAttributes.ReparsePoint
    Directory.EnumerateFiles(rootDir, "*", opts)
    |> Seq.toArray

let tryFileSize (path: string) =
    try
        let file_info = FileInfo(path)

        if file_info.Exists then
            Some file_info.Length
        else
            None
    with
    | _ -> None

let rootFull = Path.GetFullPath(rootDirectory)

if not (Directory.Exists(rootFull)) then
    failwith $"rootDirectory does not exist: {rootFull}"




let largeFiles =
    let opts = EnumerationOptions()
    opts.RecurseSubdirectories <- true
    opts.IgnoreInaccessible <- true
    opts.AttributesToSkip <- FileAttributes.ReparsePoint
    Directory.EnumerateFiles(Path.GetFullPath(rootDirectory), "*", opts)
    |> Seq.toArray
    |> Array.indexed
    |> Array.Parallel.choose (fun (index, file_path) ->

        match FileInfo(file_path) with 
        | file_info when file_info.Length >= thresholdBytes -> Some(file_path)
        | _ -> None
    
        )
    |> Array.distinct
    |> Array.sort
    |> Array.map (relativeGitPath rootFull)
    |> Array.map escapeGitignoreLine






let dotnet_gitignore = 
    """
## A streamlined .gitignore for modern .NET projects
## including temporary files, build results, and
## files generated by popular .NET tools. If you are
## developing with Visual Studio, the VS .gitignore
## https://github.com/github/gitignore/blob/main/VisualStudio.gitignore
## has more thorough IDE-specific entries.
##
## Get latest from https://github.com/github/gitignore/blob/main/Dotnet.gitignore

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Ww][Ii][Nn]32/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/

# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/

# ASP.NET Scaffolding
ScaffoldingReadMe.txt

# NuGet Packages
*.nupkg
# NuGet Symbol Packages
*.snupkg

# dotenv environment variables file
.env

# Others
~$*
*~
CodeCoverage/

# MSBuild Binary and Structured Log
*.binlog

# MSTest test Results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*

# NUnit
*.VisualState.xml
TestResult.xml
nunit-*.xml
    """



let generated_header = 
    """
# ------------------------------------------------------------
# GENERATED: ignores files >= 100 MiB
# root: {rootFull}
# ------------------------------------------------------------
    """
let generated_text = 
            if largeFiles.Length < 1 then
                "# (no files met or exceeded the threshold)"
            else
                largeFiles
                |> String.concat "\n"

let file_text =
    [| 
        authored_text.pretrimmed
        dotnet_gitignore.posttrimmed
        generated_header.circumtrimmed
        generated_text
        |]
        |> String.concat "\n"


let outputPath =
    if Path.IsPathRooted(gitignoreFilepath) then
        gitignoreFilepath
    else
        Path.Combine(rootFull, gitignoreFilepath)

Directory.CreateDirectory(Path.GetDirectoryName(outputPath))
|> ignore

File.WriteAllText(outputPath, file_text)

printfn "Scanned: %s" rootFull
printfn "Large files found: %d" largeFiles.Length
printfn "Wrote: %s" outputPath
