unicode\:Adlam -> unicode\:Block : rdf\:type
unicode\:Aegean_Numbers -> unicode\:Block : rdf\:type
unicode\:Ahom -> unicode\:Block : rdf\:type
unicode\:Alchemical_Symbols -> unicode\:Block : rdf\:type
unicode\:Alphabetic_Presentation_Forms -> unicode\:Block : rdf\:type
unicode\:Anatolian_Hieroglyphs -> unicode\:Block : rdf\:type
unicode\:Ancient_Greek_Musical_Notation -> unicode\:Block : rdf\:type
unicode\:Ancient_Greek_Numbers -> unicode\:Block : rdf\:type
unicode\:Ancient_Symbols -> unicode\:Block : rdf\:type
unicode\:Arabic -> unicode\:Block : rdf\:type
unicode\:Arabic_Extended-A -> unicode\:Block : rdf\:type
unicode\:Arabic_Extended-B -> unicode\:Block : rdf\:type
unicode\:Arabic_Extended-C -> unicode\:Block : rdf\:type
unicode\:Arabic_Mathematical_Alphabetic_Symbols -> unicode\:Block : rdf\:type
unicode\:Arabic_Presentation_Forms-A -> unicode\:Block : rdf\:type
unicode\:Arabic_Presentation_Forms-B -> unicode\:Block : rdf\:type
unicode\:Arabic_Supplement -> unicode\:Block : rdf\:type
unicode\:Armenian -> unicode\:Block : rdf\:type
unicode\:Arrows -> unicode\:Block : rdf\:type
unicode\:Avestan -> unicode\:Block : rdf\:type
unicode\:Balinese -> unicode\:Block : rdf\:type
unicode\:Bamum -> unicode\:Block : rdf\:type
unicode\:Bamum_Supplement -> unicode\:Block : rdf\:type
unicode\:Basic_Latin -> unicode\:Block : rdf\:type
unicode\:Bassa_Vah -> unicode\:Block : rdf\:type
unicode\:Batak -> unicode\:Block : rdf\:type
unicode\:Bengali -> unicode\:Block : rdf\:type
unicode\:Beria_Erfe -> unicode\:Block : rdf\:type
unicode\:Bhaiksuki -> unicode\:Block : rdf\:type
unicode\:Block_Elements -> unicode\:Block : rdf\:type
unicode\:Bopomofo -> unicode\:Block : rdf\:type
unicode\:Bopomofo_Extended -> unicode\:Block : rdf\:type
unicode\:Box_Drawing -> unicode\:Block : rdf\:type
unicode\:Brahmi -> unicode\:Block : rdf\:type
unicode\:Braille_Patterns -> unicode\:Block : rdf\:type
unicode\:Buginese -> unicode\:Block : rdf\:type
unicode\:Buhid -> unicode\:Block : rdf\:type
unicode\:Byzantine_Musical_Symbols -> unicode\:Block : rdf\:type
unicode\:CJK_Compatibility -> unicode\:Block : rdf\:type
unicode\:CJK_Compatibility_Forms -> unicode\:Block : rdf\:type
unicode\:CJK_Compatibility_Ideographs -> unicode\:Block : rdf\:type
unicode\:CJK_Compatibility_Ideographs_Supplement -> unicode\:Block : rdf\:type
unicode\:CJK_Radicals_Supplement -> unicode\:Block : rdf\:type
unicode\:CJK_Strokes -> unicode\:Block : rdf\:type
unicode\:CJK_Symbols_and_Punctuation -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs_Extension_A -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs_Extension_B -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs_Extension_C -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs_Extension_D -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs_Extension_E -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs_Extension_F -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs_Extension_G -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs_Extension_H -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs_Extension_I -> unicode\:Block : rdf\:type
unicode\:CJK_Unified_Ideographs_Extension_J -> unicode\:Block : rdf\:type
unicode\:Carian -> unicode\:Block : rdf\:type
unicode\:Caucasian_Albanian -> unicode\:Block : rdf\:type
unicode\:Chakma -> unicode\:Block : rdf\:type
unicode\:Cham -> unicode\:Block : rdf\:type
unicode\:Cherokee -> unicode\:Block : rdf\:type
unicode\:Cherokee_Supplement -> unicode\:Block : rdf\:type
unicode\:Chess_Symbols -> unicode\:Block : rdf\:type
unicode\:Chorasmian -> unicode\:Block : rdf\:type
unicode\:Combining_Diacritical_Marks -> unicode\:Block : rdf\:type
unicode\:Combining_Diacritical_Marks_Extended -> unicode\:Block : rdf\:type
unicode\:Combining_Diacritical_Marks_Supplement -> unicode\:Block : rdf\:type
unicode\:Combining_Diacritical_Marks_for_Symbols -> unicode\:Block : rdf\:type
unicode\:Combining_Half_Marks -> unicode\:Block : rdf\:type
unicode\:Common_Indic_Number_Forms -> unicode\:Block : rdf\:type
unicode\:Control_Pictures -> unicode\:Block : rdf\:type
unicode\:Coptic -> unicode\:Block : rdf\:type
unicode\:Coptic_Epact_Numbers -> unicode\:Block : rdf\:type
unicode\:Counting_Rod_Numerals -> unicode\:Block : rdf\:type
unicode\:Cuneiform -> unicode\:Block : rdf\:type
unicode\:Cuneiform_Numbers_and_Punctuation -> unicode\:Block : rdf\:type
unicode\:Currency_Symbols -> unicode\:Block : rdf\:type
unicode\:Cypriot_Syllabary -> unicode\:Block : rdf\:type
unicode\:Cypro-Minoan -> unicode\:Block : rdf\:type
unicode\:Cyrillic -> unicode\:Block : rdf\:type
unicode\:Cyrillic_Extended-A -> unicode\:Block : rdf\:type
unicode\:Cyrillic_Extended-B -> unicode\:Block : rdf\:type
unicode\:Cyrillic_Extended-C -> unicode\:Block : rdf\:type
unicode\:Cyrillic_Extended-D -> unicode\:Block : rdf\:type
unicode\:Cyrillic_Supplement -> unicode\:Block : rdf\:type
unicode\:Deseret -> unicode\:Block : rdf\:type
unicode\:Devanagari -> unicode\:Block : rdf\:type
unicode\:Devanagari_Extended -> unicode\:Block : rdf\:type
unicode\:Devanagari_Extended-A -> unicode\:Block : rdf\:type
unicode\:Dingbats -> unicode\:Block : rdf\:type
unicode\:Dives_Akuru -> unicode\:Block : rdf\:type
unicode\:Dogra -> unicode\:Block : rdf\:type
unicode\:Domino_Tiles -> unicode\:Block : rdf\:type
unicode\:Duployan -> unicode\:Block : rdf\:type
unicode\:Early_Dynastic_Cuneiform -> unicode\:Block : rdf\:type
unicode\:Egyptian_Hieroglyph_Format_Controls -> unicode\:Block : rdf\:type
unicode\:Egyptian_Hieroglyphs -> unicode\:Block : rdf\:type
unicode\:Egyptian_Hieroglyphs_Extended-A -> unicode\:Block : rdf\:type
unicode\:Elbasan -> unicode\:Block : rdf\:type
unicode\:Elymaic -> unicode\:Block : rdf\:type
unicode\:Emoticons -> unicode\:Block : rdf\:type
unicode\:Enclosed_Alphanumeric_Supplement -> unicode\:Block : rdf\:type
unicode\:Enclosed_Alphanumerics -> unicode\:Block : rdf\:type
unicode\:Enclosed_CJK_Letters_and_Months -> unicode\:Block : rdf\:type
unicode\:Enclosed_Ideographic_Supplement -> unicode\:Block : rdf\:type
unicode\:Ethiopic -> unicode\:Block : rdf\:type
unicode\:Ethiopic_Extended -> unicode\:Block : rdf\:type
unicode\:Ethiopic_Extended-A -> unicode\:Block : rdf\:type
unicode\:Ethiopic_Extended-B -> unicode\:Block : rdf\:type
unicode\:Ethiopic_Supplement -> unicode\:Block : rdf\:type
unicode\:Garay -> unicode\:Block : rdf\:type
unicode\:General_Punctuation -> unicode\:Block : rdf\:type
unicode\:Geometric_Shapes -> unicode\:Block : rdf\:type
unicode\:Geometric_Shapes_Extended -> unicode\:Block : rdf\:type
unicode\:Georgian -> unicode\:Block : rdf\:type
unicode\:Georgian_Extended -> unicode\:Block : rdf\:type
unicode\:Georgian_Supplement -> unicode\:Block : rdf\:type
unicode\:Glagolitic -> unicode\:Block : rdf\:type
unicode\:Glagolitic_Supplement -> unicode\:Block : rdf\:type
unicode\:Gothic -> unicode\:Block : rdf\:type
unicode\:Grantha -> unicode\:Block : rdf\:type
unicode\:Greek_Extended -> unicode\:Block : rdf\:type
unicode\:Greek_and_Coptic -> unicode\:Block : rdf\:type
unicode\:Gujarati -> unicode\:Block : rdf\:type
unicode\:Gunjala_Gondi -> unicode\:Block : rdf\:type
unicode\:Gurmukhi -> unicode\:Block : rdf\:type
unicode\:Gurung_Khema -> unicode\:Block : rdf\:type
unicode\:Halfwidth_and_Fullwidth_Forms -> unicode\:Block : rdf\:type
unicode\:Hangul_Compatibility_Jamo -> unicode\:Block : rdf\:type
unicode\:Hangul_Jamo -> unicode\:Block : rdf\:type
unicode\:Hangul_Jamo_Extended-A -> unicode\:Block : rdf\:type
unicode\:Hangul_Jamo_Extended-B -> unicode\:Block : rdf\:type
unicode\:Hangul_Syllables -> unicode\:Block : rdf\:type
unicode\:Hanifi_Rohingya -> unicode\:Block : rdf\:type
unicode\:Hanunoo -> unicode\:Block : rdf\:type
unicode\:Hatran -> unicode\:Block : rdf\:type
unicode\:Hebrew -> unicode\:Block : rdf\:type
unicode\:High_Private_Use_Surrogates -> unicode\:Block : rdf\:type
unicode\:High_Surrogates -> unicode\:Block : rdf\:type
unicode\:Hiragana -> unicode\:Block : rdf\:type
unicode\:IPA_Extensions -> unicode\:Block : rdf\:type
unicode\:Ideographic_Description_Characters -> unicode\:Block : rdf\:type
unicode\:Ideographic_Symbols_and_Punctuation -> unicode\:Block : rdf\:type
unicode\:Imperial_Aramaic -> unicode\:Block : rdf\:type
unicode\:Indic_Siyaq_Numbers -> unicode\:Block : rdf\:type
unicode\:Inscriptional_Pahlavi -> unicode\:Block : rdf\:type
unicode\:Inscriptional_Parthian -> unicode\:Block : rdf\:type
unicode\:Javanese -> unicode\:Block : rdf\:type
unicode\:Kaithi -> unicode\:Block : rdf\:type
unicode\:Kaktovik_Numerals -> unicode\:Block : rdf\:type
unicode\:Kana_Extended-A -> unicode\:Block : rdf\:type
unicode\:Kana_Extended-B -> unicode\:Block : rdf\:type
unicode\:Kana_Supplement -> unicode\:Block : rdf\:type
unicode\:Kanbun -> unicode\:Block : rdf\:type
unicode\:Kangxi_Radicals -> unicode\:Block : rdf\:type
unicode\:Kannada -> unicode\:Block : rdf\:type
unicode\:Katakana -> unicode\:Block : rdf\:type
unicode\:Katakana_Phonetic_Extensions -> unicode\:Block : rdf\:type
unicode\:Kawi -> unicode\:Block : rdf\:type
unicode\:Kayah_Li -> unicode\:Block : rdf\:type
unicode\:Kharoshthi -> unicode\:Block : rdf\:type
unicode\:Khitan_Small_Script -> unicode\:Block : rdf\:type
unicode\:Khmer -> unicode\:Block : rdf\:type
unicode\:Khmer_Symbols -> unicode\:Block : rdf\:type
unicode\:Khojki -> unicode\:Block : rdf\:type
unicode\:Khudawadi -> unicode\:Block : rdf\:type
unicode\:Kirat_Rai -> unicode\:Block : rdf\:type
unicode\:Lao -> unicode\:Block : rdf\:type
unicode\:Latin-1_Supplement -> unicode\:Block : rdf\:type
unicode\:Latin_Extended-A -> unicode\:Block : rdf\:type
unicode\:Latin_Extended-B -> unicode\:Block : rdf\:type
unicode\:Latin_Extended-C -> unicode\:Block : rdf\:type
unicode\:Latin_Extended-D -> unicode\:Block : rdf\:type
unicode\:Latin_Extended-E -> unicode\:Block : rdf\:type
unicode\:Latin_Extended-F -> unicode\:Block : rdf\:type
unicode\:Latin_Extended-G -> unicode\:Block : rdf\:type
unicode\:Latin_Extended_Additional -> unicode\:Block : rdf\:type
unicode\:Lepcha -> unicode\:Block : rdf\:type
unicode\:Letterlike_Symbols -> unicode\:Block : rdf\:type
unicode\:Limbu -> unicode\:Block : rdf\:type
unicode\:Linear_A -> unicode\:Block : rdf\:type
unicode\:Linear_B_Ideograms -> unicode\:Block : rdf\:type
unicode\:Linear_B_Syllabary -> unicode\:Block : rdf\:type
unicode\:Lisu -> unicode\:Block : rdf\:type
unicode\:Lisu_Supplement -> unicode\:Block : rdf\:type
unicode\:Low_Surrogates -> unicode\:Block : rdf\:type
unicode\:Lycian -> unicode\:Block : rdf\:type
unicode\:Lydian -> unicode\:Block : rdf\:type
unicode\:Mahajani -> unicode\:Block : rdf\:type
unicode\:Mahjong_Tiles -> unicode\:Block : rdf\:type
unicode\:Makasar -> unicode\:Block : rdf\:type
unicode\:Malayalam -> unicode\:Block : rdf\:type
unicode\:Mandaic -> unicode\:Block : rdf\:type
unicode\:Manichaean -> unicode\:Block : rdf\:type
unicode\:Marchen -> unicode\:Block : rdf\:type
unicode\:Masaram_Gondi -> unicode\:Block : rdf\:type
unicode\:Mathematical_Alphanumeric_Symbols -> unicode\:Block : rdf\:type
unicode\:Mathematical_Operators -> unicode\:Block : rdf\:type
unicode\:Mayan_Numerals -> unicode\:Block : rdf\:type
unicode\:Medefaidrin -> unicode\:Block : rdf\:type
unicode\:Meetei_Mayek -> unicode\:Block : rdf\:type
unicode\:Meetei_Mayek_Extensions -> unicode\:Block : rdf\:type
unicode\:Mende_Kikakui -> unicode\:Block : rdf\:type
unicode\:Meroitic_Cursive -> unicode\:Block : rdf\:type
unicode\:Meroitic_Hieroglyphs -> unicode\:Block : rdf\:type
unicode\:Miao -> unicode\:Block : rdf\:type
unicode\:Miscellaneous_Mathematical_Symbols-A -> unicode\:Block : rdf\:type
unicode\:Miscellaneous_Mathematical_Symbols-B -> unicode\:Block : rdf\:type
unicode\:Miscellaneous_Symbols -> unicode\:Block : rdf\:type
unicode\:Miscellaneous_Symbols_Supplement -> unicode\:Block : rdf\:type
unicode\:Miscellaneous_Symbols_and_Arrows -> unicode\:Block : rdf\:type
unicode\:Miscellaneous_Symbols_and_Pictographs -> unicode\:Block : rdf\:type
unicode\:Miscellaneous_Technical -> unicode\:Block : rdf\:type
unicode\:Modi -> unicode\:Block : rdf\:type
unicode\:Modifier_Tone_Letters -> unicode\:Block : rdf\:type
unicode\:Mongolian -> unicode\:Block : rdf\:type
unicode\:Mongolian_Supplement -> unicode\:Block : rdf\:type
unicode\:Mro -> unicode\:Block : rdf\:type
unicode\:Multani -> unicode\:Block : rdf\:type
unicode\:Musical_Symbols -> unicode\:Block : rdf\:type
unicode\:Myanmar -> unicode\:Block : rdf\:type
unicode\:Myanmar_Extended-A -> unicode\:Block : rdf\:type
unicode\:Myanmar_Extended-B -> unicode\:Block : rdf\:type
unicode\:Myanmar_Extended-C -> unicode\:Block : rdf\:type
unicode\:NKo -> unicode\:Block : rdf\:type
unicode\:Nabataean -> unicode\:Block : rdf\:type
unicode\:Nag_Mundari -> unicode\:Block : rdf\:type
unicode\:Nandinagari -> unicode\:Block : rdf\:type
unicode\:New_Tai_Lue -> unicode\:Block : rdf\:type
unicode\:Newa -> unicode\:Block : rdf\:type
unicode\:Number_Forms -> unicode\:Block : rdf\:type
unicode\:Nushu -> unicode\:Block : rdf\:type
unicode\:Nyiakeng_Puachue_Hmong -> unicode\:Block : rdf\:type
unicode\:Ogham -> unicode\:Block : rdf\:type
unicode\:Ol_Chiki -> unicode\:Block : rdf\:type
unicode\:Ol_Onal -> unicode\:Block : rdf\:type
unicode\:Old_Hungarian -> unicode\:Block : rdf\:type
unicode\:Old_Italic -> unicode\:Block : rdf\:type
unicode\:Old_North_Arabian -> unicode\:Block : rdf\:type
unicode\:Old_Permic -> unicode\:Block : rdf\:type
unicode\:Old_Persian -> unicode\:Block : rdf\:type
unicode\:Old_Sogdian -> unicode\:Block : rdf\:type
unicode\:Old_South_Arabian -> unicode\:Block : rdf\:type
unicode\:Old_Turkic -> unicode\:Block : rdf\:type
unicode\:Old_Uyghur -> unicode\:Block : rdf\:type
unicode\:Optical_Character_Recognition -> unicode\:Block : rdf\:type
unicode\:Oriya -> unicode\:Block : rdf\:type
unicode\:Ornamental_Dingbats -> unicode\:Block : rdf\:type
unicode\:Osage -> unicode\:Block : rdf\:type
unicode\:Osmanya -> unicode\:Block : rdf\:type
unicode\:Ottoman_Siyaq_Numbers -> unicode\:Block : rdf\:type
unicode\:Pahawh_Hmong -> unicode\:Block : rdf\:type
unicode\:Palmyrene -> unicode\:Block : rdf\:type
unicode\:Pau_Cin_Hau -> unicode\:Block : rdf\:type
unicode\:Phags-pa -> unicode\:Block : rdf\:type
unicode\:Phaistos_Disc -> unicode\:Block : rdf\:type
unicode\:Phoenician -> unicode\:Block : rdf\:type
unicode\:Phonetic_Extensions -> unicode\:Block : rdf\:type
unicode\:Phonetic_Extensions_Supplement -> unicode\:Block : rdf\:type
unicode\:Playing_Cards -> unicode\:Block : rdf\:type
unicode\:Private_Use_Area -> unicode\:Block : rdf\:type
unicode\:Psalter_Pahlavi -> unicode\:Block : rdf\:type
unicode\:Rejang -> unicode\:Block : rdf\:type
unicode\:Rumi_Numeral_Symbols -> unicode\:Block : rdf\:type
unicode\:Runic -> unicode\:Block : rdf\:type
unicode\:Samaritan -> unicode\:Block : rdf\:type
unicode\:Saurashtra -> unicode\:Block : rdf\:type
unicode\:Sharada -> unicode\:Block : rdf\:type
unicode\:Sharada_Supplement -> unicode\:Block : rdf\:type
unicode\:Shavian -> unicode\:Block : rdf\:type
unicode\:Shorthand_Format_Controls -> unicode\:Block : rdf\:type
unicode\:Siddham -> unicode\:Block : rdf\:type
unicode\:Sidetic -> unicode\:Block : rdf\:type
unicode\:Sinhala -> unicode\:Block : rdf\:type
unicode\:Sinhala_Archaic_Numbers -> unicode\:Block : rdf\:type
unicode\:Small_Form_Variants -> unicode\:Block : rdf\:type
unicode\:Small_Kana_Extension -> unicode\:Block : rdf\:type
unicode\:Sogdian -> unicode\:Block : rdf\:type
unicode\:Sora_Sompeng -> unicode\:Block : rdf\:type
unicode\:Soyombo -> unicode\:Block : rdf\:type
unicode\:Spacing_Modifier_Letters -> unicode\:Block : rdf\:type
unicode\:Specials -> unicode\:Block : rdf\:type
unicode\:Sundanese -> unicode\:Block : rdf\:type
unicode\:Sundanese_Supplement -> unicode\:Block : rdf\:type
unicode\:Sunuwar -> unicode\:Block : rdf\:type
unicode\:Superscripts_and_Subscripts -> unicode\:Block : rdf\:type
unicode\:Supplemental_Arrows-A -> unicode\:Block : rdf\:type
unicode\:Supplemental_Arrows-B -> unicode\:Block : rdf\:type
unicode\:Supplemental_Arrows-C -> unicode\:Block : rdf\:type
unicode\:Supplemental_Mathematical_Operators -> unicode\:Block : rdf\:type
unicode\:Supplemental_Punctuation -> unicode\:Block : rdf\:type
unicode\:Supplemental_Symbols_and_Pictographs -> unicode\:Block : rdf\:type
unicode\:Supplementary_Private_Use_Area-A -> unicode\:Block : rdf\:type
unicode\:Supplementary_Private_Use_Area-B -> unicode\:Block : rdf\:type
unicode\:Sutton_SignWriting -> unicode\:Block : rdf\:type
unicode\:Syloti_Nagri -> unicode\:Block : rdf\:type
unicode\:Symbols_and_Pictographs_Extended-A -> unicode\:Block : rdf\:type
unicode\:Symbols_for_Legacy_Computing -> unicode\:Block : rdf\:type
unicode\:Symbols_for_Legacy_Computing_Supplement -> unicode\:Block : rdf\:type
unicode\:Syriac -> unicode\:Block : rdf\:type
unicode\:Syriac_Supplement -> unicode\:Block : rdf\:type
unicode\:Tagalog -> unicode\:Block : rdf\:type
unicode\:Tagbanwa -> unicode\:Block : rdf\:type
unicode\:Tags -> unicode\:Block : rdf\:type
unicode\:Tai_Le -> unicode\:Block : rdf\:type
unicode\:Tai_Tham -> unicode\:Block : rdf\:type
unicode\:Tai_Viet -> unicode\:Block : rdf\:type
unicode\:Tai_Xuan_Jing_Symbols -> unicode\:Block : rdf\:type
unicode\:Tai_Yo -> unicode\:Block : rdf\:type
unicode\:Takri -> unicode\:Block : rdf\:type
unicode\:Tamil -> unicode\:Block : rdf\:type
unicode\:Tamil_Supplement -> unicode\:Block : rdf\:type
unicode\:Tangsa -> unicode\:Block : rdf\:type
unicode\:Tangut -> unicode\:Block : rdf\:type
unicode\:Tangut_Components -> unicode\:Block : rdf\:type
unicode\:Tangut_Components_Supplement -> unicode\:Block : rdf\:type
unicode\:Tangut_Supplement -> unicode\:Block : rdf\:type
unicode\:Telugu -> unicode\:Block : rdf\:type
unicode\:Thaana -> unicode\:Block : rdf\:type
unicode\:Thai -> unicode\:Block : rdf\:type
unicode\:Tibetan -> unicode\:Block : rdf\:type
unicode\:Tifinagh -> unicode\:Block : rdf\:type
unicode\:Tirhuta -> unicode\:Block : rdf\:type
unicode\:Todhri -> unicode\:Block : rdf\:type
unicode\:Tolong_Siki -> unicode\:Block : rdf\:type
unicode\:Toto -> unicode\:Block : rdf\:type
unicode\:Transport_and_Map_Symbols -> unicode\:Block : rdf\:type
unicode\:Tulu-Tigalari -> unicode\:Block : rdf\:type
unicode\:Ugaritic -> unicode\:Block : rdf\:type
unicode\:Unified_Canadian_Aboriginal_Syllabics -> unicode\:Block : rdf\:type
unicode\:Unified_Canadian_Aboriginal_Syllabics_Extended -> unicode\:Block : rdf\:type
unicode\:Unified_Canadian_Aboriginal_Syllabics_Extended-A -> unicode\:Block : rdf\:type
unicode\:Vai -> unicode\:Block : rdf\:type
unicode\:Variation_Selectors -> unicode\:Block : rdf\:type
unicode\:Variation_Selectors_Supplement -> unicode\:Block : rdf\:type
unicode\:Vedic_Extensions -> unicode\:Block : rdf\:type
unicode\:Vertical_Forms -> unicode\:Block : rdf\:type
unicode\:Vithkuqi -> unicode\:Block : rdf\:type
unicode\:Wancho -> unicode\:Block : rdf\:type
unicode\:Warang_Citi -> unicode\:Block : rdf\:type
unicode\:Yezidi -> unicode\:Block : rdf\:type
unicode\:Yi_Radicals -> unicode\:Block : rdf\:type
unicode\:Yi_Syllables -> unicode\:Block : rdf\:type
unicode\:Yijing_Hexagram_Symbols -> unicode\:Block : rdf\:type
unicode\:Zanabazar_Square -> unicode\:Block : rdf\:type
unicode\:Znamenny_Musical_Notation -> unicode\:Block : rdf\:type