namespace ResourceDescriptionFramework.rdf.Namespace

type rdf =
    static member _namespacePrefixLabel = "rdf"
    static member _distributionUriString = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    static member _namespaceUriString = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    static member Alt = "Alt"
    static member Bag = "Bag"
    static member CompoundLiteral = "CompoundLiteral"
    static member HTML = "HTML"
    static member JSON = "JSON"
    static member List = "List"
    static member PlainLiteral = "PlainLiteral"
    static member Property = "Property"
    static member Seq = "Seq"
    static member Statement = "Statement"
    static member XMLLiteral = "XMLLiteral"
    static member direction = "direction"
    static member first = "first"
    static member langString = "langString"
    static member language = "language"
    static member nil = "nil"
    static member object = "object"
    static member predicate = "predicate"
    static member rest = "rest"
    static member subject = "subject"
    static member ``type`` = "type"
    static member value = "value"
