#load @"C:\Repositories\eristocrates\ipa\Source-code\Host-environment\Common-Language-Runtime\FSharp\Interactive\DoxAletheia\RDFErgonomics.fsx"
open RDFErgonomics

module LCPW_OverlayStormwaterInfrastructure_D_WM =
    let _prefix = prefix_label "LCPW_OverlayStormwaterInfrastructure_D_WM"


    let Drainage_Network = _prefix "Drainage Network"
    let Outfall = _prefix "Outfall"
    let Stormwater_Pond = _prefix "Stormwater Pond"
    let End_Point = _prefix "End Point"
    let Inlet = _prefix "Inlet"
    let Debris_Trap = _prefix "Debris Trap"
    let Junction_Fixed = _prefix "Junction Fixed"
    let Connectivity = _prefix "Connectivity"
    let Generic_Storm_Asset = _prefix "Generic Storm Asset"
    let Stormwater_Pond_Discharge = _prefix "Stormwater Pond Discharge"
    let Private_Point = _prefix "Private Point"
    let Conduit = _prefix "Conduit"
    let Culvert_Cross_Drain = _prefix "Culvert Cross Drain"
    let Ditch_Point = _prefix "Ditch Point"
    let Ditch = _prefix "Ditch"
    let Bridge_Point = _prefix "Bridge Point"
    let Bridge = _prefix "Bridge"
    let Stormwater_Pond___Top_of_Bank = _prefix "Stormwater Pond - Top of Bank"
    let Outfall_Drainage_Area_MS4 = _prefix "Outfall Drainage Area MS4"
    let Outfall_Drainage_Area = _prefix "Outfall Drainage Area"
    let Outfall_Drainage_Area_MOF = _prefix "Outfall Drainage Area MOF"
    let Media_Points = _prefix "Media Points"
    let Damage = _prefix "Damage"
    let Non_Drainage_Network = _prefix "Non-Drainage Network"
    let Media_Points_Without_Photos = _prefix "Media Points Without Photos"
    let Interference = _prefix "Interference"
    let Pollution_Control_Box = _prefix "Pollution Control Box"
