Lexical Tokens
QuotedURI 	 ::=  	'<' URI characters (from RFC 2396) '>'
NSPrefix 	 ::=  	 NCName As defined in XML Namespace v1.1 and XML 1.1
LocalPart 	 ::=  	 NCName As defined in XML Namespace v1.1 and XML 1.1
SELECT 	 ::=  	'SELECT' 	Case Insensitive match
FROM 	 ::=  	'FROM'   	Case Insensitive match
SOURCE 	 ::=  	'SOURCE' 	Case Insensitive match
WHERE 	 ::=  	'WHERE' 	Case Insensitive match
AND 	 ::=  	'AND' 	Case Insensitive match
USING 	 ::=  	'USING' 	Case Insensitive match
Identifier 	 ::=  	([a-z][A-Z][0-9][-_.])+ 	 
EOF 	 ::=  	End of file
COMMA 	 ::=  	','
INTEGER_LITERAL  	 ::=  	([0-9])+
FLOATING_POINT_LITERAL 	 ::=  	([0-9])*'.'([0-9])+('e'('+'|'-')?([0-9])+)?
STRING_LITERAL1 	 ::=  	'"'UTF-8 characters'"' (with escaped \")
STRING_LITERAL2 	 ::=  	"'"UTF-8 characters"'" (with escaped \')
LPAREN 	 ::=  	'('
RPAREN 	 ::=  	')'
COMMA 	 ::=  	','
DOT 	 ::=  	'.'
GT 	 ::=  	'>'
LT 	 ::=  	'<'
BANG 	 ::=  	'!'
TILDE 	 ::=  	'~'
HOOK 	 ::=  	'?'
COLON 	 ::=  	':'
EQ 	 ::=  	'=='
NEQ 	 ::=  	'!='
LE 	 ::=  	'<='
GE 	 ::=  	'>='
SC_OR 	 ::=  	'||'
SC_AND 	 ::=  	'&&'
STR_EQ 	 ::= 	'EQ' 	Case Insensitive match
STR_NE 	 ::= 	'NE' 	Case Insensitive match
PLUS 	 ::=  	'+'
MINUS 	 ::=  	'-'
STAR 	 ::=  	'*'
SLASH 	 ::=  	'/'
REM 	 ::=  	'%'
STR_MATCH 	 ::=  	'=~' | '~~'
STR_NMATCH 	 ::=  	'!~'
DATATYPE 	 ::=  	'^^'
AT 	 ::=  	'@'
Grammar

References to lexical tokens are enclosed in <>.  Whitespace is skipped.

Notes: The term "literal" refers to a constant value, and not only an RDF Literal.
CompilationUnit 	 ::=  	Query <EOF>
CommaOpt 	 ::=  	( <COMMA> )?
Query 	 ::=  	SelectClause ( SourceClause )? TriplePatternClause ( ConstraintClause )? ( PrefixesClause )?
SelectClause 	 ::=  	( <SELECT> Var ( CommaOpt Var )* | <SELECT> <STAR> )
SourceClause 	 ::=  	( <SOURCE> | <FROM> ) SourceSelector ( CommaOpt SourceSelector )*
SourceSelector 	 ::=  	QName
TriplePatternClause 	 ::=  	<WHERE> TriplePattern ( CommaOpt TriplePattern )*
ConstraintClause 	 ::=  	<SUCHTHAT> Expression ( ( <COMMA> | <SUCHTHAT> ) Expression )*
TriplePattern 	 ::=  	<LPAREN> VarOrURI CommaOpt VarOrURI CommaOpt VarOrConst <RPAREN>
VarOrURI 	 ::=  	Var
	 | 	URI
VarOrConst 	 ::=  	Var
	 | 	Const
Var 	 ::=  	"?" Identifier
PrefixesClause 	 ::=  	<PREFIXES> PrefixDecl ( CommaOpt PrefixDecl )*
PrefixDecl 	 ::=  	Identifier <FOR> <QuotedURI>
Expression 	 ::=  	ConditionalOrExpression
ConditionalOrExpression 	 ::=  	ConditionalAndExpression ( <SC_OR> ConditionalAndExpression )*
ConditionalAndExpression 	 ::=  	StringEqualityExpression ( <SC_AND> StringEqualityExpression )*
StringEqualityExpression 	 ::=  	ArithmeticCondition ( <STR_EQ> ArithmeticCondition | <STR_NE> ArithmeticCondition | <STR_MATCH> PatternLiteral | <STR_NMATCH> PatternLiteral )*
ArithmeticCondition 	 ::=  	EqualityExpression
EqualityExpression 	 ::=  	RelationalExpression ( <EQ> RelationalExpression | <NEQ> RelationalExpression )?
RelationalExpression 	 ::=  	AdditiveExpression ( <LT> AdditiveExpression | <GT> AdditiveExpression | <LE> AdditiveExpression | <GE> AdditiveExpression )?
AdditiveExpression 	 ::=  	MultiplicativeExpression ( <PLUS> MultiplicativeExpression | <MINUS> MultiplicativeExpression )*
MultiplicativeExpression 	 ::=  	UnaryExpression ( <STAR> UnaryExpression | <SLASH> UnaryExpression | <REM> UnaryExpression )*
UnaryExpression 	 ::=  	UnaryExpressionNotPlusMinus
	 | 	( <PLUS> UnaryExpression | <MINUS> UnaryExpression )
UnaryExpressionNotPlusMinus 	 ::=  	( <TILDE> | <BANG> ) UnaryExpression
	 | 	PrimaryExpression
PrimaryExpression 	 ::=  	Var
	 | 	Const
	 | 	<LPAREN> Expression <RPAREN>
Const 	 ::=  	URI
	 | 	NumericLiteral
	 | 	TextLiteral
	 | 	BooleanLiteral
	 | 	NullLiteral
NumericLiteral 	 ::=  	( <INTEGER_LITERAL> | <FLOATING_POINT_LITERAL> )
TextLiteral 	 ::=  	( <STRING_LITERAL1> | <STRING_LITERAL2> ) ( <AT> Identifier )? ( <DATATYPE> URI )?
PatternLiteral 	 ::=  	
BooleanLiteral 	 ::=  	<BOOLEAN_LITERAL>
NullLiteral 	 ::=  	<NULL_LITERAL>
URI 	 ::=  	<QuotedURI>
	 |  	QName
QName 	 ::=  	<NSPrefix> ':' (<LocalPart>)?
Unlilke XML Namespaces, the local part is optional
Identifier 	 ::=  	( <IDENTIFIER> | <SELECT> | <SOURCE> | <FROM> | <WHERE> | <PREFIXES> | <FOR> | <STR_EQ> | <STR_NE> )