// PropertyValueAliases-17.0.0.txt
// Date: 2025-06-30, 06:16:21 GMT
// © 2025 Unicode®, Inc.
// Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the U.S. and other countries.
// For terms of use and license, see https://www.unicode.org/terms_of_use.html
//
// Unicode Character Database
//   For documentation, see https://www.unicode.org/reports/tr44/
//
// This file contains aliases for property values used in the UCD.
// These names can be used for XML formats of UCD data, for regular-expression
// property tests, and other programmatic textual descriptions of Unicode data.
//
// The names may be translated in appropriate environments, and additional
// aliases may be useful.
//
// FORMAT
//
// Each line describes a property value name.
// This consists of three or more fields, separated by semicolons.
//
// First Field: The first field describes the property for which that
// property value name is used.
//
// Second Field: The second field is the short name for the property value.
// It is typically an abbreviation, but in a number of cases it is simply
// a duplicate of the "long name" in the third field.
//
// Third Field: The third field is the long name for the property value,
// typically the formal name used in documentation about the property value.
//
// In the case of Canonical_Combining_Class (ccc), there are 4 fields:
// The second field is numeric, the third is the short name, and the fourth is the long name.
//
// The above are the preferred aliases. Other aliases may be listed in additional fields.
//
// Loose matching should be applied to all property names and property values, with
// the exception of String Property values. With loose matching of property names and
// values, the case distinctions, whitespace, hyphens, and '_' are ignored.
// For Numeric Property values, numeric equivalence is applied: thus "01.00"
// is equivalent to "1".
//
// NOTE: Property value names are NOT unique across properties. For example:
//
//   AL means Arabic Letter for the Bidi_Class property, and
//   AL means Above_Left for the Canonical_Combining_Class property, and
//   AL means Alphabetic for the Line_Break property.
//
// In addition, some property names may be the same as some property value names.
// For example:
//
//   sc means the Script property, and
//   Sc means the General_Category property value Currency_Symbol (Sc)
//
// The combination of property value and property name is, however, unique.
//
// For more information, see UAX #44, Unicode Character Database, and
// UTS #18, Unicode Regular Expressions.
// ================================================

#r "nuget: Prime.Ecs"

open Prime
open Prime.Ecs

// Block (blk)

let BlockAliases =
    FMap.ofArray [|


                    "Adlam", "Adlam"
                    "Aegean_Numbers", "Aegean_Numbers"
                    "Ahom", "Ahom"
                    "Alchemical", "Alchemical_Symbols"
                    "Alphabetic_PF", "Alphabetic_Presentation_Forms"
                    "Anatolian_Hieroglyphs", "Anatolian_Hieroglyphs"
                    "Ancient_Greek_Music", "Ancient_Greek_Musical_Notation"
                    "Ancient_Greek_Numbers", "Ancient_Greek_Numbers"
                    "Ancient_Symbols", "Ancient_Symbols"
                    "Arabic", "Arabic"
                    "Arabic_Ext_A", "Arabic_Extended_A"
                    "Arabic_Ext_B", "Arabic_Extended_B"
                    "Arabic_Ext_C", "Arabic_Extended_C"
                    "Arabic_Math", "Arabic_Mathematical_Alphabetic_Symbols"
                    "Arabic_PF_A", "Arabic_Presentation_Forms_A" // Arabic_Presentation_Forms-A
                    "Arabic_PF_B", "Arabic_Presentation_Forms_B"
                    "Arabic_Sup", "Arabic_Supplement"
                    "Armenian", "Armenian"
                    "Arrows", "Arrows"
                    "ASCII", "Basic_Latin"
                    "Avestan", "Avestan"
                    "Balinese", "Balinese"
                    "Bamum", "Bamum"
                    "Bamum_Sup", "Bamum_Supplement"
                    "Bassa_Vah", "Bassa_Vah"
                    "Batak", "Batak"
                    "Bengali", "Bengali"
                    "Beria_Erfe", "Beria_Erfe"
                    "Bhaiksuki", "Bhaiksuki"
                    "Block_Elements", "Block_Elements"
                    "Bopomofo", "Bopomofo"
                    "Bopomofo_Ext", "Bopomofo_Extended"
                    "Box_Drawing", "Box_Drawing"
                    "Brahmi", "Brahmi"
                    "Braille", "Braille_Patterns"
                    "Buginese", "Buginese"
                    "Buhid", "Buhid"
                    "Byzantine_Music", "Byzantine_Musical_Symbols"
                    "Carian", "Carian"
                    "Caucasian_Albanian", "Caucasian_Albanian"
                    "Chakma", "Chakma"
                    "Cham", "Cham"
                    "Cherokee", "Cherokee"
                    "Cherokee_Sup", "Cherokee_Supplement"
                    "Chess_Symbols", "Chess_Symbols"
                    "Chorasmian", "Chorasmian"
                    "CJK", "CJK_Unified_Ideographs"
                    "CJK_Compat", "CJK_Compatibility"
                    "CJK_Compat_Forms", "CJK_Compatibility_Forms"
                    "CJK_Compat_Ideographs", "CJK_Compatibility_Ideographs"
                    "CJK_Compat_Ideographs_Sup", "CJK_Compatibility_Ideographs_Supplement"
                    "CJK_Ext_A", "CJK_Unified_Ideographs_Extension_A"
                    "CJK_Ext_B", "CJK_Unified_Ideographs_Extension_B"
                    "CJK_Ext_C", "CJK_Unified_Ideographs_Extension_C"
                    "CJK_Ext_D", "CJK_Unified_Ideographs_Extension_D"
                    "CJK_Ext_E", "CJK_Unified_Ideographs_Extension_E"
                    "CJK_Ext_F", "CJK_Unified_Ideographs_Extension_F"
                    "CJK_Ext_G", "CJK_Unified_Ideographs_Extension_G"
                    "CJK_Ext_H", "CJK_Unified_Ideographs_Extension_H"
                    "CJK_Ext_I", "CJK_Unified_Ideographs_Extension_I"
                    "CJK_Ext_J", "CJK_Unified_Ideographs_Extension_J"
                    "CJK_Radicals_Sup", "CJK_Radicals_Supplement"
                    "CJK_Strokes", "CJK_Strokes"
                    "CJK_Symbols", "CJK_Symbols_And_Punctuation"
                    "Compat_Jamo", "Hangul_Compatibility_Jamo"
                    "Control_Pictures", "Control_Pictures"
                    "Coptic", "Coptic"
                    "Coptic_Epact_Numbers", "Coptic_Epact_Numbers"
                    "Counting_Rod", "Counting_Rod_Numerals"
                    "Cuneiform", "Cuneiform"
                    "Cuneiform_Numbers", "Cuneiform_Numbers_And_Punctuation"
                    "Currency_Symbols", "Currency_Symbols"
                    "Cypriot_Syllabary", "Cypriot_Syllabary"
                    "Cypro_Minoan", "Cypro_Minoan"
                    "Cyrillic", "Cyrillic"
                    "Cyrillic_Ext_A", "Cyrillic_Extended_A"
                    "Cyrillic_Ext_B", "Cyrillic_Extended_B"
                    "Cyrillic_Ext_C", "Cyrillic_Extended_C"
                    "Cyrillic_Ext_D", "Cyrillic_Extended_D"
                    "Cyrillic_Sup", "Cyrillic_Supplement" // Cyrillic_Supplementary
                    "Deseret", "Deseret"
                    "Devanagari", "Devanagari"
                    "Devanagari_Ext", "Devanagari_Extended"
                    "Devanagari_Ext_A", "Devanagari_Extended_A"
                    "Diacriticals", "Combining_Diacritical_Marks"
                    "Diacriticals_Ext", "Combining_Diacritical_Marks_Extended"
                    "Diacriticals_For_Symbols", "Combining_Diacritical_Marks_For_Symbols" // Combining_Marks_For_Symbols
                    "Diacriticals_Sup", "Combining_Diacritical_Marks_Supplement"
                    "Dingbats", "Dingbats"
                    "Dives_Akuru", "Dives_Akuru"
                    "Dogra", "Dogra"
                    "Domino", "Domino_Tiles"
                    "Duployan", "Duployan"
                    "Early_Dynastic_Cuneiform", "Early_Dynastic_Cuneiform"
                    "Egyptian_Hieroglyph_Format_Controls", "Egyptian_Hieroglyphs"
                    "Egyptian_Hieroglyphs_Ext_A", "Egyptian_Hieroglyphs_Extended_A"
                    "Elbasan", "Elbasan"
                    "Elymaic", "Elymaic"
                    "Emoticons", "Emoticons"
                    "Enclosed_Alphanum", "Enclosed_Alphanumerics"
                    "Enclosed_Alphanum_Sup", "Enclosed_Alphanumeric_Supplement"
                    "Enclosed_CJK", "Enclosed_CJK_Letters_And_Months"
                    "Enclosed_Ideographic_Sup", "Enclosed_Ideographic_Supplement"
                    "Ethiopic", "Ethiopic"
                    "Ethiopic_Ext", "Ethiopic_Extended"
                    "Ethiopic_Ext_A", "Ethiopic_Extended_A"
                    "Ethiopic_Ext_B", "Ethiopic_Extended_B"
                    "Ethiopic_Sup", "Ethiopic_Supplement"
                    "Garay", "Garay"
                    "Geometric_Shapes", "Geometric_Shapes"
                    "Geometric_Shapes_Ext", "Geometric_Shapes_Extended"
                    "Georgian", "Georgian"
                    "Georgian_Ext", "Georgian_Extended"
                    "Georgian_Sup", "Georgian_Supplement"
                    "Glagolitic", "Glagolitic"
                    "Glagolitic_Sup", "Glagolitic_Supplement"
                    "Gothic", "Gothic"
                    "Grantha", "Grantha"
                    "Greek", "Greek_And_Coptic"
                    "Greek_Ext", "Greek_Extended"
                    "Gujarati", "Gujarati"
                    "Gunjala_Gondi", "Gunjala_Gondi"
                    "Gurmukhi", "Gurmukhi"
                    "Gurung_Khema", "Gurung_Khema"
                    "Half_And_Full_Forms", "Halfwidth_And_Fullwidth_Forms"
                    "Half_Marks", "Combining_Half_Marks"
                    "Hangul", "Hangul_Syllables"
                    "Hanifi_Rohingya", "Hanifi_Rohingya"
                    "Hanunoo", "Hanunoo"
                    "Hatran", "Hatran"
                    "Hebrew", "Hebrew"
                    "High_PU_Surrogates", "High_Private_Use_Surrogates"
                    "High_Surrogates", "High_Surrogates"
                    "Hiragana", "Hiragana"
                    "IDC", "Ideographic_Description_Characters"
                    "Ideographic_Symbols", "Ideographic_Symbols_And_Punctuation"
                    "Imperial_Aramaic", "Imperial_Aramaic"
                    "Indic_Number_Forms", "Common_Indic_Number_Forms"
                    "Indic_Siyaq_Numbers", "Indic_Siyaq_Numbers"
                    "Inscriptional_Pahlavi", "Inscriptional_Pahlavi"
                    "Inscriptional_Parthian", "Inscriptional_Parthian"
                    "IPA_Ext", "IPA_Extensions"
                    "Jamo", "Hangul_Jamo"
                    "Jamo_Ext_A", "Hangul_Jamo_Extended_A"
                    "Jamo_Ext_B", "Hangul_Jamo_Extended_B"
                    "Javanese", "Javanese"
                    "Kaithi", "Kaithi"
                    "Kaktovik_Numerals", "Kaktovik_Numerals"
                    "Kana_Ext_A", "Kana_Extended_A"
                    "Kana_Ext_B", "Kana_Extended_B"
                    "Kana_Sup", "Kana_Supplement"
                    "Kanbun", "Kanbun"
                    "Kangxi", "Kangxi_Radicals"
                    "Kannada", "Kannada"
                    "Katakana", "Katakana"
                    "Katakana_Ext", "Katakana_Phonetic_Extensions"
                    "Kawi", "Kawi"
                    "Kayah_Li", "Kayah_Li"
                    "Kharoshthi", "Kharoshthi"
                    "Khitan_Small_Script", "Khitan_Small_Script"
                    "Khmer", "Khmer"
                    "Khmer_Symbols", "Khmer_Symbols"
                    "Khojki", "Khojki"
                    "Khudawadi", "Khudawadi"
                    "Kirat_Rai", "Kirat_Rai"
                    "Lao", "Lao"
                    "Latin_1_Sup", "Latin_1_Supplement" // Latin_1
                    "Latin_Ext_A", "Latin_Extended_A"
                    "Latin_Ext_Additional", "Latin_Extended_Additional"
                    "Latin_Ext_B", "Latin_Extended_B"
                    "Latin_Ext_C", "Latin_Extended_C"
                    "Latin_Ext_D", "Latin_Extended_D"
                    "Latin_Ext_E", "Latin_Extended_E"
                    "Latin_Ext_F", "Latin_Extended_F"
                    "Latin_Ext_G", "Latin_Extended_G"
                    "Lepcha", "Lepcha"
                    "Letterlike_Symbols", "Letterlike_Symbols"
                    "Limbu", "Limbu"
                    "Linear_A", "Linear_A"
                    "Linear_B_Ideograms", "Linear_B_Ideograms"
                    "Linear_B_Syllabary", "Linear_B_Syllabary"
                    "Lisu", "Lisu"
                    "Lisu_Sup", "Lisu_Supplement"
                    "Low_Surrogates", "Low_Surrogates"
                    "Lycian", "Lycian"
                    "Lydian", "Lydian"
                    "Mahajani", "Mahajani"
                    "Mahjong", "Mahjong_Tiles"
                    "Makasar", "Makasar"
                    "Malayalam", "Malayalam"
                    "Mandaic", "Mandaic"
                    "Manichaean", "Manichaean"
                    "Marchen", "Marchen"
                    "Masaram_Gondi", "Masaram_Gondi"
                    "Math_Alphanum", "Mathematical_Alphanumeric_Symbols"
                    "Math_Operators", "Mathematical_Operators"
                    "Mayan_Numerals", "Mayan_Numerals"
                    "Medefaidrin", "Medefaidrin"
                    "Meetei_Mayek", "Meetei_Mayek"
                    "Meetei_Mayek_Ext", "Meetei_Mayek_Extensions"
                    "Mende_Kikakui", "Mende_Kikakui"
                    "Meroitic_Cursive", "Meroitic_Cursive"
                    "Meroitic_Hieroglyphs", "Meroitic_Hieroglyphs"
                    "Miao", "Miao"
                    "Misc_Arrows", "Miscellaneous_Symbols_And_Arrows"
                    "Misc_Math_Symbols_A", "Miscellaneous_Mathematical_Symbols_A"
                    "Misc_Math_Symbols_B", "Miscellaneous_Mathematical_Symbols_B"
                    "Misc_Pictographs", "Miscellaneous_Symbols_And_Pictographs"
                    "Misc_Symbols", "Miscellaneous_Symbols"
                    "Misc_Symbols_Sup", "Miscellaneous_Symbols_Supplement"
                    "Misc_Technical", "Miscellaneous_Technical"
                    "Modi", "Modi"
                    "Modifier_Letters", "Spacing_Modifier_Letters"
                    "Modifier_Tone_Letters", "Modifier_Tone_Letters"
                    "Mongolian", "Mongolian"
                    "Mongolian_Sup", "Mongolian_Supplement"
                    "Mro", "Mro"
                    "Multani", "Multani"
                    "Music", "Musical_Symbols"
                    "Myanmar", "Myanmar"
                    "Myanmar_Ext_A", "Myanmar_Extended_A"
                    "Myanmar_Ext_B", "Myanmar_Extended_B"
                    "Myanmar_Ext_C", "Myanmar_Extended_C"
                    "Nabataean", "Nabataean"
                    "Nag_Mundari", "Nag_Mundari"
                    "Nandinagari", "Nandinagari"
                    "NB", "No_Block"
                    "New_Tai_Lue", "New_Tai_Lue"
                    "Newa", "Newa"
                    "NKo", "NKo"
                    "Number_Forms", "Number_Forms"
                    "Nushu", "Nushu"
                    "Nyiakeng_Puachue_Hmong", "Nyiakeng_Puachue_Hmong"
                    "OCR", "Optical_Character_Recognition"
                    "Ogham", "Ogham"
                    "Ol_Chiki", "Ol_Chiki"
                    "Ol_Onal", "Ol_Onal"
                    "Old_Hungarian", "Old_Hungarian"
                    "Old_Italic", "Old_Italic"
                    "Old_North_Arabian", "Old_North_Arabian"
                    "Old_Permic", "Old_Permic"
                    "Old_Persian", "Old_Persian"
                    "Old_Sogdian", "Old_Sogdian"
                    "Old_South_Arabian", "Old_South_Arabian"
                    "Old_Turkic", "Old_Turkic"
                    "Old_Uyghur", "Old_Uyghur"
                    "Oriya", "Oriya"
                    "Ornamental_Dingbats", "Ornamental_Dingbats"
                    "Osage", "Osage"
                    "Osmanya", "Osmanya"
                    "Ottoman_Siyaq_Numbers", "Ottoman_Siyaq_Numbers"
                    "Pahawh_Hmong", "Pahawh_Hmong"
                    "Palmyrene", "Palmyrene"
                    "Pau_Cin_Hau", "Pau_Cin_Hau"
                    "Phags_Pa", "Phags_Pa"
                    "Phaistos", "Phaistos_Disc"
                    "Phoenician", "Phoenician"
                    "Phonetic_Ext", "Phonetic_Extensions"
                    "Phonetic_Ext_Sup", "Phonetic_Extensions_Supplement"
                    "Playing_Cards", "Playing_Cards"
                    "Psalter_Pahlavi", "Psalter_Pahlavi"
                    "PUA", "Private_Use_Area" // Private_Use
                    "Punctuation", "General_Punctuation"
                    "Rejang", "Rejang"
                    "Rumi", "Rumi_Numeral_Symbols"
                    "Runic", "Runic"
                    "Samaritan", "Samaritan"
                    "Saurashtra", "Saurashtra"
                    "Sharada", "Sharada"
                    "Sharada_Sup", "Sharada_Supplement"
                    "Shavian", "Shavian"
                    "Shorthand_Format_Controls", "Shorthand_Format_Controls"
                    "Siddham", "Siddham"
                    "Sidetic", "Sidetic"
                    "Sinhala", "Sinhala"
                    "Sinhala_Archaic_Numbers", "Sinhala_Archaic_Numbers"
                    "Small_Forms", "Small_Form_Variants"
                    "Small_Kana_Ext", "Small_Kana_Extension"
                    "Sogdian", "Sogdian"
                    "Sora_Sompeng", "Sora_Sompeng"
                    "Soyombo", "Soyombo"
                    "Specials", "Specials"
                    "Sundanese", "Sundanese"
                    "Sundanese_Sup", "Sundanese_Supplement"
                    "Sunuwar", "Sunuwar"
                    "Sup_Arrows_A", "Supplemental_Arrows_A"
                    "Sup_Arrows_B", "Supplemental_Arrows_B"
                    "Sup_Arrows_C", "Supplemental_Arrows_C"
                    "Sup_Math_Operators", "Supplemental_Mathematical_Operators"
                    "Sup_PUA_A", "Supplementary_Private_Use_Area_A"
                    "Sup_PUA_B", "Supplementary_Private_Use_Area_B"
                    "Sup_Punctuation", "Supplemental_Punctuation"
                    "Sup_Symbols_And_Pictographs", "Supplemental_Symbols_And_Pictographs"
                    "Super_And_Sub", "Superscripts_And_Subscripts"
                    "Sutton_SignWriting", "Sutton_SignWriting"
                    "Syloti_Nagri", "Syloti_Nagri"
                    "Symbols_And_Pictographs_Ext_A", "Symbols_And_Pictographs_Extended_A"
                    "Symbols_For_Legacy_Computing", "Symbols_For_Legacy_Computing"
                    "Symbols_For_Legacy_Computing_Sup", "Symbols_For_Legacy_Computing_Supplement"
                    "Syriac", "Syriac"
                    "Syriac_Sup", "Syriac_Supplement"
                    "Tagalog", "Tagalog"
                    "Tagbanwa", "Tagbanwa"
                    "Tags", "Tags"
                    "Tai_Le", "Tai_Le"
                    "Tai_Tham", "Tai_Tham"
                    "Tai_Viet", "Tai_Viet"
                    "Tai_Xuan_Jing", "Tai_Xuan_Jing_Symbols"
                    "Tai_Yo", "Tai_Yo"
                    "Takri", "Takri"
                    "Tamil", "Tamil"
                    "Tamil_Sup", "Tamil_Supplement"
                    "Tangsa", "Tangsa"
                    "Tangut", "Tangut"
                    "Tangut_Components", "Tangut_Components"
                    "Tangut_Components_Sup", "Tangut_Components_Supplement"
                    "Tangut_Sup", "Tangut_Supplement"
                    "Telugu", "Telugu"
                    "Thaana", "Thaana"
                    "Thai", "Thai"
                    "Tibetan", "Tibetan"
                    "Tifinagh", "Tifinagh"
                    "Tirhuta", "Tirhuta"
                    "Todhri", "Todhri"
                    "Tolong_Siki", "Tolong_Siki"
                    "Toto", "Toto"
                    "Transport_And_Map", "Transport_And_Map_Symbols"
                    "Tulu_Tigalari", "Tulu_Tigalari"
                    "UCAS", "Unified_Canadian_Aboriginal_Syllabics" // Canadian_Syllabics
                    "UCAS_Ext", "Unified_Canadian_Aboriginal_Syllabics_Extended"
                    "UCAS_Ext_A", "Unified_Canadian_Aboriginal_Syllabics_Extended_A"
                    "Ugaritic", "Ugaritic"
                    "Vai", "Vai"
                    "Vedic_Ext", "Vedic_Extensions"
                    "Vertical_Forms", "Vertical_Forms"
                    "Vithkuqi", "Vithkuqi"
                    "VS", "Variation_Selectors"
                    "VS_Sup", "Variation_Selectors_Supplement"
                    "Wancho", "Wancho"
                    "Warang_Citi", "Warang_Citi"
                    "Yezidi", "Yezidi"
                    "Yi_Radicals", "Yi_Radicals"
                    "Yi_Syllables", "Yi_Syllables"
                    "Yijing", "Yijing_Hexagram_Symbols"
                    "Zanabazar_Square", "Zanabazar_Square"
                    "Znamenny_Music", "Znamenny_Musical_Notation" |]
