<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net8.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Interval_Range.fs" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Update="FSharp.Core" Version="8.0.403" />
    <PackageReference Include="FRange" Version="1.1.0" />
    <PackageReference Include="NeatIntervals" Version="1.0.0" />
  </ItemGroup>

</Project>
