// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("IanaProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("IanaProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing IanaProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "IanaProvider.Runtime"
    let [<Literal>] AssemblyProduct = "IanaProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing IanaProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
