<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <FSharpToolsDirectory>typeproviders</FSharpToolsDirectory>
    <PackagePath>typeproviders</PackagePath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs">
    </Compile>
    <Compile Include="LanguageSubtag.fs">
    </Compile>
    <Compile Include="MyProvider.Runtime.fs">
    </Compile>
    <Compile Include="MimeTypes.fs">
    </Compile>
    <Compile Include="MimePath.fs">
    </Compile>
    <Compile Include="MimeSubstring.fs">
    </Compile>
    <Compile Include="Iana_Schemes.fs">
    </Compile>
    <None Include="paket.references">
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="8.0.403">
    </PackageReference>
    <ProjectReference Include="..\..\..\..\Solution\DoxAletheia\Unicodepoint\Unicodepoint.fsproj">
    </ProjectReference>
    <ProjectReference Include="..\..\..\..\Solution\DoxAletheia\Interval_Range\Interval_Range.fsproj">
    </ProjectReference>
    <ProjectReference Include="..\..\..\..\Solution\DoxAletheia\ParserCombinator\ParserCombinator.fsproj">
    </ProjectReference>
    <ProjectReference Include="..\MyProvider.DesignTime\MyProvider.DesignTime.fsproj">
      <IsFSharpDesignTimeProvider>true</IsFSharpDesignTimeProvider>
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
  </ItemGroup>
  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>