<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <FSharpToolsDirectory>typeproviders</FSharpToolsDirectory>
    <PackagePath>typeproviders</PackagePath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs">
    </Compile>
    <Compile Include="IanaProvider.Runtime.fs">
    </Compile>
    <None Include="paket.references">
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="4.7.2">
    </PackageReference>
    <ProjectReference Include="..\IanaProvider.DesignTime\IanaProvider.DesignTime.fsproj">
      <IsFSharpDesignTimeProvider>true</IsFSharpDesignTimeProvider>
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
  </ItemGroup>
  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>