SELECT *
FROM OPENQUERY(
    [HRORACLEPROD],
    '
    SELECT
        SYS_CONTEXT(''USERENV'', ''DB_NAME'')       AS DATABASE_NAME,
        SYS_CONTEXT(''USERENV'', ''SERVICE_NAME'')  AS SERVICE_NAME,
        SYS_CONTEXT(''USERENV'', ''INSTANCE_NAME'') AS INSTANCE_NAME,
        SYS_CONTEXT(''USERENV'', ''SERVER_HOST'')   AS SERVER_HOST,
        SYS_CONTEXT(''USERENV'', ''SESSION_USER'')  AS SESSION_USER,
        SYS_CONTEXT(''USERENV'', ''AUTHENTICATION_METHOD'')
            AS AUTHENTICATION_METHOD
    FROM DUAL
    '
);