<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Html_Entities.fs" />
    <Compile Include="Unicodepoint.fs" />
  </ItemGroup>

  <ItemGroup>
	  
    <ProjectReference Include="..\Ergonomic_Extensions\Ergonomic_Extensions.fsproj" />
  </ItemGroup>

	
</Project>
