<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net8.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Html_Entities.fs" />
    <Compile Include="Unicodepoint.fs" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Update="FSharp.Core" Version="8.0.403" />
    <ProjectReference Include="..\Ergonomic_Extensions\Ergonomic_Extensions.fsproj" />
  </ItemGroup>

	
</Project>
