<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    
    
    
    <Compile Include="Language\Meta\Bacus_Naur_Form\Augmented\ABNF.fs" />
	  <Compile Include="Identifier\Resource\Uniform\URI.fs" />
	<Compile Include="Identifier\Resource\Internationalized\IRI.fs" />
	  <Compile Include="Language\Markup\Extensible\XML.fs" />
	  <Compile Include="Model\Resource_Description_Framework\Notation3_Lineage\Turtle\Turtle.fs" />
  </ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="XParsec" Version="0.4.0" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\Ergonomics\Ergonomics.fsproj" />
	  <ProjectReference Include="..\Unicodepoint\Unicodepoint.fsproj" />
	</ItemGroup>
	
</Project>
