<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Punctuation.fs" />
    <Compile Include="ArabicNumerals.fs" />
    <Compile Include="LatinAlphabet.fs" />
  </ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="XParsec" Version="0.4.0" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\Ergonomics\Ergonomics.fsproj" />
	</ItemGroup>
	
</Project>
