graph LR
  0["LCPW_OverlayStormwaterInfrastructure_D_WM:Stormwater_Pond"]
  1["2^^xsd:long"]
  2["LCPW_OverlayStormwaterInfrastructure_D_WM:Media_Points"]
  3["577790.554289^^xsd:double"]
  4["LCPW_OverlayStormwaterInfrastructure_D_WM:MapServer"]
  5["LCPW_OverlayStormwaterInfrastructure_D_WM:Private_Point"]
  6["LCPW_OverlayStormwaterInfrastructure_D_WM:Ditch_Point"]
  7["Ditch Point^^xsd:string"]
  8["LCPW_OverlayStormwaterInfrastructure_D_WM:Stormwater_Pond_-_Top_of_Bank"]
  9["1^^xsd:double"]
  10["LCPW_OverlayStormwaterInfrastructure_D_WM:Connectivity"]
  11["4096^^xsd:int"]
  12["LCPW_OverlayStormwaterInfrastructure_D_WM:Outfall_Drainage_Area"]
  13["true^^xsd:boolean"]
  14["LCPW_OverlayStormwaterInfrastructure_D_WM:Ditch"]
  15["LCPW_OverlayStormwaterInfrastructure_D_WM:Bridge"]
  16["LCPW_OverlayStormwaterInfrastructure_D_WM:Interference"]
  17["LCPW_OverlayStormwaterInfrastructure_D_WM:Damage"]
  18["Loaded"]
  19["LCPW_OverlayStormwaterInfrastructure_D_WM:Drainage_Network"]
  20["Drainage Network^^xsd:string"]
  21["false^^xsd:boolean"]
  22["LCPW_OverlayStormwaterInfrastructure_D_WM:Bridge"]
  23["LCPW_OverlayStormwaterInfrastructure_D_WM:End_Point"]
  24["3^^xsd:long"]
  25["LCPW_OverlayStormwaterInfrastructure_D_WM:Culvert_Cross_Drain"]
  26["LCPW_OverlayStormwaterInfrastructure_D_WM:Generic_Storm_Asset"]
  27["LCPW_OverlayStormwaterInfrastructure_D_WM:Pollution_Control_Box"]
  28["LCPW_OverlayStormwaterInfrastructure_D_WM:Outfall"]
  29["LCPW_OverlayStormwaterInfrastructure_D_WM:Ditch"]
  30["https://interraster.leoncountyfl.gov/interraster/rest/services/MapServices/LCPW_OverlayStormwaterInfrastructure_D_WM/MapServer^^xsd:anyURI"]
  31["LCPW_OverlayStormwaterInfrastructure_D_WM:Ditch_Point"]
  32["14^^xsd:long"]
  33["LCPW_OverlayStormwaterInfrastructure_D_WM:Junction_Fixed"]
  34["LCPW_OverlayStormwaterInfrastructure_D_WM:Media_Points"]
  35["LCPW_OverlayStormwaterInfrastructure_D_WM:Non-Drainage_Network"]
  36["23^^xsd:long"]
  37["LCPW_OverlayStormwaterInfrastructure_D_WM:Stormwater_Pond_Discharge"]
  38["LCPW_OverlayStormwaterInfrastructure_D_WM:Debris_Trap"]
  39["0^^xsd:double"]
  40["Stormwater Pond Discharge^^xsd:string"]
  41["LCPW_OverlayStormwaterInfrastructure_D_WM:Media_Points_Without_Photos"]
  42["24^^xsd:long"]
  43["End Point^^xsd:string"]
  44["LCPW_OverlayStormwaterInfrastructure_D_WM:Culvert_Cross_Drain"]
  45["Media Points^^xsd:string"]
  46["owl:NamedIndividual"]
  47["LCPW_OverlayStormwaterInfrastructure_D_WM:Inlet"]
  48["LCPW_OverlayStormwaterInfrastructure_D_WM:Pollution_Control_Box"]
  49["LCPW_OverlayStormwaterInfrastructure_D_WM:Private_Point"]
  50["16^^xsd:long"]
  51["LCPW_OverlayStormwaterInfrastructure_D_WM:Bridge_Point"]
  52["15^^xsd:long"]
  53["LCPW_OverlayStormwaterInfrastructure_D_WM:Outfall_Drainage_Area_MOF"]
  54["Bridge^^xsd:string"]
  55["AkkM8jgyQnKwhGKarBP5OQ^^xsd:ID"]
  56["LCPW_OverlayStormwaterInfrastructure_D_WM:Conduit"]
  57["Non-Drainage Network^^xsd:string"]
  58["Layers^^xsd:string"]
  59["1^^xsd:long"]
  60["Outfall^^xsd:string"]
  61["Private Point^^xsd:string"]
  62["LCPW_OverlayStormwaterInfrastructure_D_WM:Outfall_Drainage_Area_MS4"]
  63["18^^xsd:long"]
  64["LCPW_OverlayStormwaterInfrastructure_D_WM:Outfall_Drainage_Area_MOF"]
  65["LCPW_OverlayStormwaterInfrastructure_D_WM:End_Point"]
  66["LCPW_OverlayStormwaterInfrastructure_D_WM:Damage"]
  67["LCPW_OverlayStormwaterInfrastructure_D_WM:Junction_Fixed"]
  68["12^^xsd:long"]
  69["LCPW_OverlayStormwaterInfrastructure_D_WM:Non-Drainage_Network"]
  70["11^^xsd:long"]
  71["5^^xsd:long"]
  72["LCPW OverlayStormwaterInfrastructure D WM^^xsd:string"]
  73["Interference^^xsd:string"]
  74["20^^xsd:long"]
  75["Damage^^xsd:string"]
  76["Conduit^^xsd:string"]
  77["0^^xsd:long"]
  78["LCPW_OverlayStormwaterInfrastructure_D_WM:Debris_Trap"]
  79["6^^xsd:long"]
  80["Outfall Drainage Area^^xsd:string"]
  81["8^^xsd:long"]
  82["LCPW_OverlayStormwaterInfrastructure_D_WM:Inlet"]
  83["7^^xsd:long"]
  84["Junction Fixed^^xsd:string"]
  85["LCPW_OverlayStormwaterInfrastructure_D_WM:Generic_Storm_Asset"]
  86["4^^xsd:long"]
  87["Bridge Point^^xsd:string"]
  88["Inlet^^xsd:string"]
  89["0^^xsd:int"]
  90["Media Points Without Photos^^xsd:string"]
  91["13^^xsd:long"]
  92["LCPW_OverlayStormwaterInfrastructure_D_WM:Drainage_Network"]
  93["10.81^^xsd:string"]
  94["22^^xsd:long"]
  95["LCPW_OverlayStormwaterInfrastructure_D_WM:Interference"]
  96["Stormwater Pond^^xsd:string"]
  97["LCPW_OverlayStormwaterInfrastructure_D_WM:Outfall_Drainage_Area_MS4"]
  98["LCPW_OverlayStormwaterInfrastructure_D_WM:Stormwater_Pond_Discharge"]
  99["PT0S^^xsd:duration"]
  100["Outfall Drainage Area MOF^^xsd:string"]
  101["9^^xsd:long"]
  102["LCPW_OverlayStormwaterInfrastructure_D_WM:Stormwater_Pond_-_Top_of_Bank"]
  103["Stormwater Pond - Top of Bank^^xsd:string"]
  104["LCPW_OverlayStormwaterInfrastructure_D_WM:Bridge_Point"]
  105["3000^^xsd:int"]
  106["Generic Storm Asset^^xsd:string"]
  107["LCPW_OverlayStormwaterInfrastructure_D_WM:Connectivity"]
  108["LCPW_OverlayStormwaterInfrastructure_D_WM:Stormwater_Pond"]
  109["Pollution Control Box^^xsd:string"]
  110["Outfall Drainage Area MS4^^xsd:string"]
  111["19^^xsd:long"]
  112["Culvert Cross Drain^^xsd:string"]
  113["21^^xsd:long"]
  114["ArcGISRuntime:Esri.ArcGISRuntime.Mapping.ArcGISMapImageLayer"]
  115["Debris Trap^^xsd:string"]
  116["LCPW_OverlayStormwaterInfrastructure_D_WM:Outfall_Drainage_Area"]
  117["LCPW_OverlayStormwaterInfrastructure_D_WM:Conduit"]
  118["Ditch^^xsd:string"]
  119["Connectivity^^xsd:string"]
  120["LCPW_OverlayStormwaterInfrastructure_D_WM:Outfall"]
  121["10^^xsd:long"]
  122["26^^xsd:long"]
  123["25^^xsd:long"]
  124["LCPW_OverlayStormwaterInfrastructure_D_WM:Media_Points_Without_Photos"]
  125["17^^xsd:long"]
  126["This map service layer (image layer) contains storm-water inventory for unincorporated Leon County that has been developed from a variety of sources. It contains FDOT and Leon County inventory features as well as some private connections. It falls into roughly 4 categories.

1 – That which was produced by LCPW vendors.
- Limitations with this set include bad geometry – meaning either not snapped or incorrect feature types. Table data present but not assessed.

2 – Drawn in by TLCGIS staff according to as-built documents (typically areas with more complex sub-surface drainage conditions).
- Very good geometry with somewhat less robust attribute data.

3 – Drawn in by TLCGIS staff using a combination of Google Street View, 2018 DEM/Hillshade, various aerial imagery data and other data sources such as drainage easements. These reflect areas of relatively simple drainage conditions such as culverts, MES, headwalls, Spillways, etc.
- Primary limitation being there is very little attribute data and also includes disconnected surface features that need as-builts to complete.

4 – Drawn in by TLCGIS staff that represent neighborhood drainage conditions.
- These are exclusively geometry with no real attribute data. Mostly this is mostly culverts and associated end sections where identifiable.

All data is drawn in direction of flow. Guess work has been mitigated by using Google Street View, over 10 years of various aerial imagery and DEM results to carefully place features in their actual locations. The vendor data uses GPS and is less well positioned. Any locations where unincorporated data from as-builts intersects with COTSW inventory has not been drawn in but rather connected to (snapped) to the COTSW data. *If you are a Leon County Engineer and you need access to COTSW inventory data that can be arranged. COTSW data will however not be included in the Public Works or DSEM web mapping applications.
^^xsd:string"]
  127["ArcGISRuntime:Esri.ArcGISRuntime.Mapping.ArcGISMapImageLayer"]
  128["owl:Class"]
  0 -->|"ArcGISRuntime:id"| 1
  0 -->|"ArcGISRuntime:min_scale"| 3
  0 -->|"ArcGISRuntime:opacity"| 9
  0 -->|"ArcGISRuntime:is_popup_enabled"| 13
  0 -->|"ArcGISRuntime:load_status"| 18
  0 -->|"ArcGISRuntime:scale_symbols"| 21
  0 -->|"ArcGISRuntime:max_scale"| 39
  0 -->|"ArcGISRuntime:name"| 96
  2 -->|"ArcGISRuntime:min_scale"| 3
  2 -->|"ArcGISRuntime:opacity"| 9
  2 -->|"ArcGISRuntime:is_popup_enabled"| 13
  2 -->|"ArcGISRuntime:load_status"| 18
  2 -->|"ArcGISRuntime:labels_enabled"| 21
  2 -->|"ArcGISRuntime:max_scale"| 39
  2 -->|"ArcGISRuntime:name"| 45
  2 -->|"ArcGISRuntime:id"| 113
  4 -->|"ArcGISRuntime:min_scale"| 3
  4 -->|"ArcGISRuntime:sublayer"| 5
  4 -->|"ArcGISRuntime:opacity"| 9
  4 -->|"ArcGISRuntime:max_image_height"| 11
  4 -->|"ArcGISRuntime:show_in_legend"| 13
  4 -->|"ArcGISRuntime:sublayer"| 14
  4 -->|"ArcGISRuntime:sublayer"| 15
  4 -->|"ArcGISRuntime:load_status"| 18
  4 -->|"ArcGISRuntime:single_fused_map_cache"| 21
  4 -->|"ArcGISRuntime:sublayer"| 25
  4 -->|"ArcGISRuntime:sublayer"| 27
  4 -->|"ArcGISRuntime:source"| 30
  4 -->|"ArcGISRuntime:sublayer"| 31
  4 -->|"ArcGISRuntime:sublayer"| 34
  4 -->|"ArcGISRuntime:gamma"| 39
  4 -->|"a"| 46
  4 -->|"ArcGISRuntime:id"| 55
  4 -->|"ArcGISRuntime:map_name"| 58
  4 -->|"ArcGISRuntime:sublayer"| 64
  4 -->|"ArcGISRuntime:sublayer"| 65
  4 -->|"ArcGISRuntime:sublayer"| 66
  4 -->|"ArcGISRuntime:sublayer"| 67
  4 -->|"ArcGISRuntime:sublayer"| 69
  4 -->|"ArcGISRuntime:name"| 72
  4 -->|"ArcGISRuntime:sublayer"| 78
  4 -->|"ArcGISRuntime:sublayer"| 82
  4 -->|"ArcGISRuntime:sublayer"| 85
  4 -->|"ArcGISRuntime:max_export_tiles_count"| 89
  4 -->|"ArcGISRuntime:sublayer"| 92
  4 -->|"ArcGISRuntime:current_version"| 93
  4 -->|"ArcGISRuntime:sublayer"| 95
  4 -->|"ArcGISRuntime:sublayer"| 97
  4 -->|"ArcGISRuntime:sublayer"| 98
  4 -->|"ArcGISRuntime:refresh_interval"| 99
  4 -->|"ArcGISRuntime:sublayer"| 102
  4 -->|"ArcGISRuntime:sublayer"| 104
  4 -->|"ArcGISRuntime:max_record_count"| 105
  4 -->|"ArcGISRuntime:sublayer"| 107
  4 -->|"ArcGISRuntime:sublayer"| 108
  4 -->|"a"| 114
  4 -->|"ArcGISRuntime:sublayer"| 116
  4 -->|"ArcGISRuntime:sublayer"| 117
  4 -->|"ArcGISRuntime:sublayer"| 120
  4 -->|"ArcGISRuntime:sublayer"| 124
  4 -->|"ArcGISRuntime:service_description"| 126
  6 -->|"ArcGISRuntime:min_scale"| 3
  6 -->|"ArcGISRuntime:name"| 7
  6 -->|"ArcGISRuntime:opacity"| 9
  6 -->|"ArcGISRuntime:default_visibility"| 13
  6 -->|"ArcGISRuntime:load_status"| 18
  6 -->|"ArcGISRuntime:scale_symbols"| 21
  6 -->|"ArcGISRuntime:max_scale"| 39
  6 -->|"ArcGISRuntime:id"| 91
  8 -->|"ArcGISRuntime:min_scale"| 3
  8 -->|"ArcGISRuntime:opacity"| 9
  8 -->|"ArcGISRuntime:default_visibility"| 13
  8 -->|"ArcGISRuntime:load_status"| 18
  8 -->|"ArcGISRuntime:scale_symbols"| 21
  8 -->|"ArcGISRuntime:max_scale"| 39
  8 -->|"ArcGISRuntime:name"| 103
  8 -->|"ArcGISRuntime:id"| 125
  10 -->|"ArcGISRuntime:min_scale"| 3
  10 -->|"ArcGISRuntime:opacity"| 9
  10 -->|"ArcGISRuntime:is_popup_enabled"| 13
  10 -->|"ArcGISRuntime:load_status"| 18
  10 -->|"ArcGISRuntime:labels_enabled"| 21
  10 -->|"ArcGISRuntime:max_scale"| 39
  10 -->|"ArcGISRuntime:id"| 83
  10 -->|"ArcGISRuntime:name"| 119
  12 -->|"ArcGISRuntime:min_scale"| 3
  12 -->|"ArcGISRuntime:opacity"| 9
  12 -->|"ArcGISRuntime:show_in_legend"| 13
  12 -->|"ArcGISRuntime:load_status"| 18
  12 -->|"ArcGISRuntime:labels_enabled"| 21
  12 -->|"ArcGISRuntime:max_scale"| 39
  12 -->|"ArcGISRuntime:name"| 80
  12 -->|"ArcGISRuntime:id"| 111
  16 -->|"ArcGISRuntime:min_scale"| 3
  16 -->|"ArcGISRuntime:opacity"| 9
  16 -->|"ArcGISRuntime:is_visible"| 13
  16 -->|"ArcGISRuntime:load_status"| 18
  16 -->|"ArcGISRuntime:labels_enabled"| 21
  16 -->|"ArcGISRuntime:max_scale"| 39
  16 -->|"ArcGISRuntime:name"| 73
  16 -->|"ArcGISRuntime:id"| 123
  17 -->|"ArcGISRuntime:min_scale"| 3
  17 -->|"ArcGISRuntime:opacity"| 9
  17 -->|"ArcGISRuntime:default_visibility"| 13
  17 -->|"ArcGISRuntime:load_status"| 18
  17 -->|"ArcGISRuntime:labels_enabled"| 21
  17 -->|"ArcGISRuntime:max_scale"| 39
  17 -->|"ArcGISRuntime:name"| 75
  17 -->|"ArcGISRuntime:id"| 94
  19 -->|"ArcGISRuntime:opacity"| 9
  19 -->|"ArcGISRuntime:show_in_legend"| 13
  19 -->|"ArcGISRuntime:load_status"| 18
  19 -->|"ArcGISRuntime:name"| 20
  19 -->|"ArcGISRuntime:labels_enabled"| 21
  19 -->|"ArcGISRuntime:min_scale"| 39
  19 -->|"ArcGISRuntime:id"| 77
  22 -->|"ArcGISRuntime:min_scale"| 3
  22 -->|"ArcGISRuntime:opacity"| 9
  22 -->|"ArcGISRuntime:is_popup_enabled"| 13
  22 -->|"ArcGISRuntime:load_status"| 18
  22 -->|"ArcGISRuntime:labels_enabled"| 21
  22 -->|"ArcGISRuntime:max_scale"| 39
  22 -->|"ArcGISRuntime:id"| 50
  22 -->|"ArcGISRuntime:name"| 54
  23 -->|"ArcGISRuntime:min_scale"| 3
  23 -->|"ArcGISRuntime:opacity"| 9
  23 -->|"ArcGISRuntime:default_visibility"| 13
  23 -->|"ArcGISRuntime:load_status"| 18
  23 -->|"ArcGISRuntime:labels_enabled"| 21
  23 -->|"ArcGISRuntime:id"| 24
  23 -->|"ArcGISRuntime:max_scale"| 39
  23 -->|"ArcGISRuntime:name"| 43
  26 -->|"ArcGISRuntime:min_scale"| 3
  26 -->|"ArcGISRuntime:opacity"| 9
  26 -->|"ArcGISRuntime:is_popup_enabled"| 13
  26 -->|"ArcGISRuntime:load_status"| 18
  26 -->|"ArcGISRuntime:labels_enabled"| 21
  26 -->|"ArcGISRuntime:max_scale"| 39
  26 -->|"ArcGISRuntime:id"| 81
  26 -->|"ArcGISRuntime:name"| 106
  28 -->|"ArcGISRuntime:min_scale"| 3
  28 -->|"ArcGISRuntime:opacity"| 9
  28 -->|"ArcGISRuntime:default_visibility"| 13
  28 -->|"ArcGISRuntime:load_status"| 18
  28 -->|"ArcGISRuntime:labels_enabled"| 21
  28 -->|"ArcGISRuntime:max_scale"| 39
  28 -->|"ArcGISRuntime:id"| 59
  28 -->|"ArcGISRuntime:name"| 60
  29 -->|"ArcGISRuntime:min_scale"| 3
  29 -->|"ArcGISRuntime:opacity"| 9
  29 -->|"ArcGISRuntime:is_visible"| 13
  29 -->|"ArcGISRuntime:load_status"| 18
  29 -->|"ArcGISRuntime:labels_enabled"| 21
  29 -->|"ArcGISRuntime:id"| 32
  29 -->|"ArcGISRuntime:max_scale"| 39
  29 -->|"ArcGISRuntime:name"| 118
  33 -->|"ArcGISRuntime:min_scale"| 3
  33 -->|"ArcGISRuntime:opacity"| 9
  33 -->|"ArcGISRuntime:default_visibility"| 13
  33 -->|"ArcGISRuntime:load_status"| 18
  33 -->|"ArcGISRuntime:scale_symbols"| 21
  33 -->|"ArcGISRuntime:max_scale"| 39
  33 -->|"ArcGISRuntime:id"| 79
  33 -->|"ArcGISRuntime:name"| 84
  35 -->|"ArcGISRuntime:opacity"| 9
  35 -->|"ArcGISRuntime:show_in_legend"| 13
  35 -->|"ArcGISRuntime:load_status"| 18
  35 -->|"ArcGISRuntime:labels_enabled"| 21
  35 -->|"ArcGISRuntime:id"| 36
  35 -->|"ArcGISRuntime:min_scale"| 39
  35 -->|"ArcGISRuntime:name"| 57
  37 -->|"ArcGISRuntime:min_scale"| 3
  37 -->|"ArcGISRuntime:opacity"| 9
  37 -->|"ArcGISRuntime:show_in_legend"| 13
  37 -->|"ArcGISRuntime:load_status"| 18
  37 -->|"ArcGISRuntime:labels_enabled"| 21
  37 -->|"ArcGISRuntime:max_scale"| 39
  37 -->|"ArcGISRuntime:name"| 40
  37 -->|"ArcGISRuntime:id"| 101
  38 -->|"ArcGISRuntime:min_scale"| 3
  38 -->|"ArcGISRuntime:opacity"| 9
  38 -->|"ArcGISRuntime:default_visibility"| 13
  38 -->|"ArcGISRuntime:load_status"| 18
  38 -->|"ArcGISRuntime:labels_enabled"| 21
  38 -->|"ArcGISRuntime:max_scale"| 39
  38 -->|"ArcGISRuntime:id"| 71
  38 -->|"ArcGISRuntime:name"| 115
  41 -->|"ArcGISRuntime:min_scale"| 3
  41 -->|"ArcGISRuntime:opacity"| 9
  41 -->|"ArcGISRuntime:is_popup_enabled"| 13
  41 -->|"ArcGISRuntime:load_status"| 18
  41 -->|"ArcGISRuntime:labels_enabled"| 21
  41 -->|"ArcGISRuntime:max_scale"| 39
  41 -->|"ArcGISRuntime:id"| 42
  41 -->|"ArcGISRuntime:name"| 90
  44 -->|"ArcGISRuntime:min_scale"| 3
  44 -->|"ArcGISRuntime:opacity"| 9
  44 -->|"ArcGISRuntime:default_visibility"| 13
  44 -->|"ArcGISRuntime:load_status"| 18
  44 -->|"ArcGISRuntime:labels_enabled"| 21
  44 -->|"ArcGISRuntime:max_scale"| 39
  44 -->|"ArcGISRuntime:id"| 68
  44 -->|"ArcGISRuntime:name"| 112
  47 -->|"ArcGISRuntime:min_scale"| 3
  47 -->|"ArcGISRuntime:opacity"| 9
  47 -->|"ArcGISRuntime:show_in_legend"| 13
  47 -->|"ArcGISRuntime:load_status"| 18
  47 -->|"ArcGISRuntime:labels_enabled"| 21
  47 -->|"ArcGISRuntime:max_scale"| 39
  47 -->|"ArcGISRuntime:id"| 86
  47 -->|"ArcGISRuntime:name"| 88
  48 -->|"ArcGISRuntime:min_scale"| 3
  48 -->|"ArcGISRuntime:opacity"| 9
  48 -->|"ArcGISRuntime:default_visibility"| 13
  48 -->|"ArcGISRuntime:load_status"| 18
  48 -->|"ArcGISRuntime:labels_enabled"| 21
  48 -->|"ArcGISRuntime:max_scale"| 39
  48 -->|"ArcGISRuntime:name"| 109
  48 -->|"ArcGISRuntime:id"| 122
  49 -->|"ArcGISRuntime:min_scale"| 3
  49 -->|"ArcGISRuntime:opacity"| 9
  49 -->|"ArcGISRuntime:show_in_legend"| 13
  49 -->|"ArcGISRuntime:load_status"| 18
  49 -->|"ArcGISRuntime:labels_enabled"| 21
  49 -->|"ArcGISRuntime:max_scale"| 39
  49 -->|"ArcGISRuntime:name"| 61
  49 -->|"ArcGISRuntime:id"| 121
  51 -->|"ArcGISRuntime:min_scale"| 3
  51 -->|"ArcGISRuntime:opacity"| 9
  51 -->|"ArcGISRuntime:default_visibility"| 13
  51 -->|"ArcGISRuntime:load_status"| 18
  51 -->|"ArcGISRuntime:labels_enabled"| 21
  51 -->|"ArcGISRuntime:max_scale"| 39
  51 -->|"ArcGISRuntime:id"| 52
  51 -->|"ArcGISRuntime:name"| 87
  53 -->|"ArcGISRuntime:min_scale"| 3
  53 -->|"ArcGISRuntime:opacity"| 9
  53 -->|"ArcGISRuntime:show_in_legend"| 13
  53 -->|"ArcGISRuntime:load_status"| 18
  53 -->|"ArcGISRuntime:is_visible"| 21
  53 -->|"ArcGISRuntime:max_scale"| 39
  53 -->|"ArcGISRuntime:id"| 74
  53 -->|"ArcGISRuntime:name"| 100
  56 -->|"ArcGISRuntime:min_scale"| 3
  56 -->|"ArcGISRuntime:opacity"| 9
  56 -->|"ArcGISRuntime:is_popup_enabled"| 13
  56 -->|"ArcGISRuntime:load_status"| 18
  56 -->|"ArcGISRuntime:labels_enabled"| 21
  56 -->|"ArcGISRuntime:max_scale"| 39
  56 -->|"ArcGISRuntime:id"| 70
  56 -->|"ArcGISRuntime:name"| 76
  62 -->|"ArcGISRuntime:min_scale"| 3
  62 -->|"ArcGISRuntime:opacity"| 9
  62 -->|"ArcGISRuntime:is_popup_enabled"| 13
  62 -->|"ArcGISRuntime:load_status"| 18
  62 -->|"ArcGISRuntime:labels_enabled"| 21
  62 -->|"ArcGISRuntime:max_scale"| 39
  62 -->|"ArcGISRuntime:id"| 63
  62 -->|"ArcGISRuntime:name"| 110
  127 -->|"a"| 128
