LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> 2^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> Ditch Point^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 4096^^xsd\:int : ArcGISRuntime\:max_image_width
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> Drainage Network^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> 3^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> https://interraster.leoncountyfl.gov/interraster/rest/services/MapServices/LCPW_OverlayStormwaterInfrastructure_D_WM/MapServer^^xsd\:anyURI : ArcGISRuntime\:source
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> 14^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> 23^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> Stormwater Pond Discharge^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> 24^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> End Point^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> Media Points^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> false^^xsd\:boolean : ArcGISRuntime\:export_tiles_allowed
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> owl\:NamedIndividual : a
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> 16^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> 15^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> false^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> Bridge^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> AkkM8jgyQnKwhGKarBP5OQ^^xsd\:ID : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> Non-Drainage Network^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> Layers^^xsd\:string : ArcGISRuntime\:map_name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> 1^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> Outfall^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> Private Point^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> 18^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> false^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> 12^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> false^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> false^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> 11^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> 5^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW OverlayStormwaterInfrastructure D WM^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> Interference^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> 20^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> true^^xsd\:boolean : ArcGISRuntime\:supports_dynamic_layers
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> true^^xsd\:boolean : ArcGISRuntime\:is_identify_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> Damage^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> Conduit^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> 0^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> 6^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> Outfall Drainage Area^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> 8^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> 7^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> Junction Fixed^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> false^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> 4^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> Bridge Point^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> true^^xsd\:boolean : ArcGISRuntime\:is_time_filtering_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> Inlet^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> false^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> false^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 0^^xsd\:int : ArcGISRuntime\:max_export_tiles_count
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> Media Points Without Photos^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> 13^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 0^^xsd\:double : ArcGISRuntime\:contrast
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 10.81^^xsd\:string : ArcGISRuntime\:current_version
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> false^^xsd\:boolean : ArcGISRuntime\:supports_time_filtering
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> 22^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> Stormwater Pond^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> PT0S^^xsd\:duration : ArcGISRuntime\:refresh_interval
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> true^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> Outfall Drainage Area MOF^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> 9^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> false^^xsd\:boolean : ArcGISRuntime\:export_tile_cache_compact_v2allowed
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> Stormwater Pond - Top of Bank^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 3000^^xsd\:int : ArcGISRuntime\:max_record_count
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> Generic Storm Asset^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> Pollution Control Box^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> Outfall Drainage Area MS4^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> 19^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 0^^xsd\:double : ArcGISRuntime\:brightness
LCPW_OverlayStormwaterInfrastructure_D_WM\:Damage -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> Culvert Cross Drain^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> 21^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> ArcGISRuntime\:Esri.ArcGISRuntime.Mapping.ArcGISMapImageLayer : a
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> Debris Trap^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Culvert_Cross_Drain -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> 0^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> Ditch^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:Junction_Fixed -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Generic_Storm_Asset -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch_Point -> 1^^xsd\:double : ArcGISRuntime\:opacity
LCPW_OverlayStormwaterInfrastructure_D_WM\:Drainage_Network -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> Connectivity^^xsd\:string : ArcGISRuntime\:name
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> false^^xsd\:boolean : ArcGISRuntime\:single_fused_map_cache
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MOF -> false^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:End_Point -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> 10^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Pollution_Control_Box -> 26^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_Discharge -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> 0^^xsd\:double : ArcGISRuntime\:max_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> 25^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Interference -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points_Without_Photos : ArcGISRuntime\:sublayer
LCPW_OverlayStormwaterInfrastructure_D_WM\:Ditch -> true^^xsd\:boolean : ArcGISRuntime\:is_visible
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> 17^^xsd\:long : ArcGISRuntime\:id
LCPW_OverlayStormwaterInfrastructure_D_WM\:Inlet -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge_Point -> true^^xsd\:boolean : ArcGISRuntime\:default_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> 0^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 0^^xsd\:double : ArcGISRuntime\:gamma
LCPW_OverlayStormwaterInfrastructure_D_WM\:Private_Point -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> This map service layer (image layer) contains storm-water inventory for unincorporated Leon County that has been developed from a variety of sources. It contains FDOT and Leon County inventory features as well as some private connections. It falls into roughly 4 categories.

1 – That which was produced by LCPW vendors.
- Limitations with this set include bad geometry – meaning either not snapped or incorrect feature types. Table data present but not assessed.

2 – Drawn in by TLCGIS staff according to as-built documents (typically areas with more complex sub-surface drainage conditions).
- Very good geometry with somewhat less robust attribute data.

3 – Drawn in by TLCGIS staff using a combination of Google Street View, 2018 DEM/Hillshade, various aerial imagery data and other data sources such as drainage easements. These reflect areas of relatively simple drainage conditions such as culverts, MES, headwalls, Spillways, etc.
- Primary limitation being there is very little attribute data and also includes disconnected surface features that need as-builts to complete.

4 – Drawn in by TLCGIS staff that represent neighborhood drainage conditions.
- These are exclusively geometry with no real attribute data. Mostly this is mostly culverts and associated end sections where identifiable.

All data is drawn in direction of flow. Guess work has been mitigated by using Google Street View, over 10 years of various aerial imagery and DEM results to carefully place features in their actual locations. The vendor data uses GPS and is less well positioned. Any locations where unincorporated data from as-builts intersects with COTSW inventory has not been drawn in but rather connected to (snapped) to the COTSW data. *If you are a Leon County Engineer and you need access to COTSW inventory data that can be arranged. COTSW data will however not be included in the Public Works or DSEM web mapping applications.
^^xsd\:string : ArcGISRuntime\:service_description
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> 4096^^xsd\:int : ArcGISRuntime\:max_image_height
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:MapServer -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> true^^xsd\:boolean : ArcGISRuntime\:can_change_visibility
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> false^^xsd\:boolean : ArcGISRuntime\:scale_symbols
LCPW_OverlayStormwaterInfrastructure_D_WM\:Outfall_Drainage_Area_MS4 -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Conduit -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Non-Drainage_Network -> true^^xsd\:boolean : ArcGISRuntime\:show_in_legend
ArcGISRuntime\:Esri.ArcGISRuntime.Mapping.ArcGISMapImageLayer -> owl\:Class : a
LCPW_OverlayStormwaterInfrastructure_D_WM\:Media_Points -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond -> 577790.554289^^xsd\:double : ArcGISRuntime\:min_scale
LCPW_OverlayStormwaterInfrastructure_D_WM\:Connectivity -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Stormwater_Pond_-_Top_of_Bank -> Loaded : ArcGISRuntime\:load_status
LCPW_OverlayStormwaterInfrastructure_D_WM\:Debris_Trap -> false^^xsd\:boolean : ArcGISRuntime\:labels_enabled
LCPW_OverlayStormwaterInfrastructure_D_WM\:Bridge -> true^^xsd\:boolean : ArcGISRuntime\:is_popup_enabled