namespace PaketLoadScripts

#load "Avalonia.Remote.Protocol.fsx" 
#load "MicroCom.Runtime.fsx" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.MicroCom.dll" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.Base.dll" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.dll" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.Vulkan.dll" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.Metal.dll" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.Markup.dll" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.Controls.dll" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.OpenGL.dll" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.Markup.Xaml.dll" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.Dialogs.dll" 
#r "../../packages/Avalonia/lib/net10.0/Avalonia.DesignerSupport.dll" 