Grammar

There are no reserved words in the Algae grammar. Variables may be called ?ask or ?namespace.

The Algae grammar starts with the query production:
query &mdash an Algae query string
[1]    	query 	   ::=    	(actionStr
| '@' sourceStr)*
An algae query is made up of actions and include directives. Include directives identify a URL or file whose contents are to be included in the query. The query processor replaces all include directives with the actions resulting from parsing the included resource. A resource may be included more than once, however, circular inclusions are a CircularInclusionException.

@foaf-query.alg
collect (?who ?knowsWho)

actionStr &mdash Algae functions
[2]    	actionStr 	   ::=    	askStr
| attachStr
| collectStr
| namespaceStr
| requireStr
| slurpStr
[3]    	askStr 	   ::=    	'ask' dbSpec? '(' graphPattern '.'? ')'
The ask directive identifies a query pattern and optionally database in which to attempt to match that pattern.

ask <http://example.com/annotationsDB>
    (?a rdf:type a:Annotation
     ?a a:annotates <http://example.com/some/page.html>)

[4]    	attachStr 	   ::=    	'attach' urlvar urlvarlit '(' binding* ')'
This provides the parameters necessary for attaching to a database and determines the handle used to subsequently identify this database. The first parameter is a URL which identifies a database. This document reserves the name http://www.w3.org/2004/05/06-Algae/#ephemoral to refer to a memory resident database. The second parameter is the handle. The handle may be either a URL or a variable. The third parameter is a set of zero or more bindings (see bindings below).

attach <http://www.w3.org/2003/01/21-RDF-RDB-access/ns#dbs> ot:db (
                    properties="OrderTracking.prop")

The parameters are determined by the type of the database.
[5]    	collectStr 	   ::=    	('collect' | 'select') '(' knownVar+ ')'
Identify a set of variables to report.

collect (?name ?mbox)

[6]    	namespaceStr 	   ::=    	('ns' | 'namespace') namespaceDecl
Specify a namespace prefix associated with a namespace.

ns a=<http://www.w3.org/2000/10/annotation-ns#>

[7]    	slurpStr 	   ::=    	('slurp' | 'read') sourceStr dbSpec? '(' binding* ')'
Import statements from the sourceStr. The sources of these statements will often be an RDF document, but need not be.

read <http://example.org/someWebPage> (user="bob" password="obo")

[8]    	requireStr 	   ::=    	'require' url
Specify a profile that the query server must support in order to satisfy this query.

require <http://www.w3.org/2004/06/20-rules/#rule>

decl &mdash statement declaration
Algae uses a subset of the Notation 3 [4] syntax to define a graph pattern. This subset includes only the syntax for making assertions with constants or variables. The following productions define the syntax for that syntax.
[9]    	decl 	   ::=    	subject propValueList
A single decl specifies that each result in the result set be replaced by (zero or more) results obtained from the following two steps:
1 Substitute the variables from that result for the variables in the decl and search for the resulting triple in the (current) database.
2 Evaluate the constraints on the triples obtained from step 1.
[10]    	propValueList 	   ::=    	property valueList
| propValueList ';' property valueList
[11]    	valueList 	   ::=    	value ('{' expr '}')*
| valueList ',' value ('{' expr '}')*
[12]    	subject 	   ::=    	urlvar
| '[' nulPropValList ']'
[13]    	value 	   ::=    	urlvarlit
| '[' nulPropValList ']'
[14]    	nulPropValList 	   ::=    	
| propValueList
| propValueList '.'
| propValueList ';' '.'
[15]    	property 	   ::=    	urlvar
For example, the following is a valid algae decl:

<#pat> <#child>  <#al>, <#chaz>, <#mo> ;
       <#age>    24 ;
       <#eyecolor> "blue" .

graphPattern &mdash represent a set of graphs
The graphPattern expresses a set of graphs with logical connectives.
[16]    	graphPattern 	   ::=    	QTerm
| graphPattern '.' graphPattern
| graphPattern '.'? '||' graphPattern
| graphPattern '.'? '|&' graphPattern
| graphPattern '.'? '|-' graphPattern
The "." connective indicates a conjunction, ie. the construction of a graph. However, when combined with the other connectives ("||", "|&", "|-"), it has no meaning — the pattern has the same meaning as if no "." were present. It is included only for ease in authoring queries.
A single QTerm specifies that each result in the result set be replaced by (zero or more) results obtained by evaluating the QTerm.
The conjunction connective, ".", specifies that each result in the result set be replaced by the (zero or more) results obtained by evaluating each graph pattern in the conjunction.
The shortcut disjunction connective, "||", specifies that each result in the result set be replaced by the (zero or more) results obtained by either, evaluating the left graph pattern in the conjunction, or, if the left pattern produced no results, evaluating the right graph pattern.
The union disjunction connective, "|&", specifies that each result in the result set be replaced by the union of the results from evaluating the left graph pattern and evaluating the right graph pattern.
The merged union disjunction connective, "|-", specifies that each result in the result set be replaced by the results from evaluating the left graph pattern and merged with the results from evaluating the right graph pattern. This merging operation reduces duplicate result tuples to a single result with that tuple with the proofs from both merged results. This conjunction is not in the core profile, but is in the sortable profile.

?annotation rdfs:type a:Annotation .
(?annotation d0:title ?title ||
 ?annotation d1:title ?title).

[17]    	QTerm 	   ::=    	decl
| '(' graphPattern '.'? ')'
| '~' QTerm
| '!' decl
expr &mdash expressions operating on atoms within a decl
exprs provide arithmetic and comparison functions on elements within the statement data model.
[18]    	expr 	   ::=    	expr '*' expr
| expr '/' expr
| expr '%' expr
| expr '+' expr
| expr '-' expr
| expr '<' expr
| expr '>' expr
| expr '<=' expr
| expr '>=' expr
| expr '==' expr
| expr '!=' expr
| expr '&' expr
| expr '^' expr
| expr '|' expr
| expr '&&' expr
| expr '||' expr
| single
| varOrName '=' expr
| varOrName '@' str
[19]    	single 	   ::=    	'-' single UMINUS
| '!' single
| '~' single
| '(' expr ')'
| internalName
| variable
| literal
| url
convenience productions
[20]    	namespaceDecl 	   ::=    	name '=' url
| url
[21]    	sourceStr 	   ::=    	url
| filename
[22]    	varOrName 	   ::=    	variable
| internalName
[23]    	internalName 	   ::=    	'%' name
[24]    	urlvar 	   ::=    	url
| variable
[25]    	urlvarlit 	   ::=    	urlvar
| literal
| internalName
[26]    	variable 	   ::=    	'?' variableName
[27]    	knownVar 	   ::=    	'?' variableName
[28]    	variableName 	   ::=    	VAR
[29]    	literal 	   ::=    	str
| INT
| FLOAT
| DtSTR url
[30]    	str 	   ::=    	STR
[31]    	binding 	   ::=    	name '=' urlvarlit
| internalName '=' urlvarlit
[32]    	name 	   ::=    	VAR
[33]    	dbSpec 	   ::=    	url
| variable
[34]    	filename 	   ::=    	FILE
[35]    	url 	   ::=    	URL
| qname
[36]    	qname 	   ::=    	VAR ':' VAR
| VAR
terminals
in order of precedence:
[T1]    	URL 	   ::=    	'<' space* ([^space>]+) space* '>'
[T2]    	DtSTR 	   ::=    	'"' ([^"]+) '"'^^
| "'" ([^']+) "'"^^
[T3]    	STR 	   ::=    	'"' ([^"]+) '"'
| "'" ([^']+) "'"
[T4]    	FLOAT 	   ::=    	[0-9]* '.' [0-9]+
[T5]    	INT 	   ::=    	[0-9]+
[T6]    	VAR 	   ::=    	[A-Za-z][A-Za-z0-9_]+