<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>	  
	  
	  <Compile Include="Namespace_Prefixes.fs" />
	  <Compile Include="LanguageTag.fs" />
	  <Compile Include="Types.fs" />
	  <Compile Include="MimeTypes.fs" />
	  <Compile Include="MimePath.fs" />
	  <Compile Include="MimeSubstring.fs" />
	  <Compile Include=".\xsd.fs" />
	  <Compile Include=".\Manual\xml.fs" /> 
	  <Compile Include=".\Manual\xsi.fs" />
	  <Compile Include=".\Manual\xdt.fs" />
	  <Compile Include=".\Generated\*.fs" />
	  <Compile Include="Rdf_Literal.fs" />
	  <Compile Include="Rdf_Document.fs" />
	  <Compile Include="Rdf_Shorthand.fs" />
	  <Compile Include="Data_Store.fs" />
	  

  </ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Unquote" Version="7.0.1" />
		<PackageReference Include="Yog.FSharp" Version="0.6.0" />
		<PackageReference Include="GraphShape" Version="1.2.1" />
		<PackageReference Include="QuikGraph" Version="2.5.0" />
		<PackageReference Include="QuikGraph.Graphviz" Version="2.5.0" />
		<PackageReference Include="QuikGraph.Serialization" Version="2.5.0" />
		<PackageReference Include="QuikGraph.Data" Version="2.5.0" />
		<PackageReference Include="QuikGraph.MSAGL" Version="2.5.0" />
		<PackageReference Include="QuikGraph.Petri" Version="2.5.0" />
		<PackageReference Include="dotNetRdf" Version="3.5.2" />
		<PackageReference Include="Iride" Version="0.6.1" />
		<PackageReference Include="FSharp.HashCollections" Version="0.3.4" />
		<PackageReference Include="Blake3" Version="3.0.1" />
		<PackageReference Include="LightningDB" Version="0.22.0" />
		<PackageReference Include="BitFaster.Caching" Version="2.6.0" />
		<PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.2" />
		<PackageReference Include="FSharp.UMX" Version="1.1.0" />

		
	</ItemGroup>
	
  <ItemGroup>
	  
    <ProjectReference Include="..\Ergonomic_Extensions\Ergonomic_Extensions.fsproj" />
    <ProjectReference Include="..\Interval_Range\Interval_Range.fsproj" />
    <ProjectReference Include="..\ParserCombinator\ParserCombinator.fsproj" />
    <ProjectReference Include="..\Unicodepoint\Unicodepoint.fsproj" />
  </ItemGroup>

</Project>
