<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
	
  </PropertyGroup>

  <ItemGroup>
	  <Compile Include="Generate.fs" />
	  <Compile Include="Generated\*.fs" />
	  


	  

  </ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="FSharp.Collections.ParallelSeq" Version="1.2.0" />
		<PackageReference Update="FSharp.Core" Version="10.0.102" />
		<PackageReference Include="FSharp.Data.Adaptive" Version="1.2.26" />
		<PackageReference Include="Unquote" Version="7.0.1" />
		<PackageReference Include="FSharp.Json" Version="0.4.1" />
		<PackageReference Include="FSharp.Data.Json" Version="1.0.0" />
		<PackageReference Include="FSharp.Data.JsonPath" Version="1.1.3" />
		<PackageReference Include="Fleece" Version="0.11.0-static-interfaces.1" />
		<PackageReference Include="FSharpPlus" Version="1.9.1" />
		<PackageReference Include="Fleece.FSharpData" Version="0.11.0-static-interfaces.1" />
		<PackageReference Include="FsHttp" Version="15.0.3" />
		<PackageReference Include="FsHttp.NewtonsoftJson" Version="15.0.3" />
		<PackageReference Include="FsHttp.FSharpData" Version="15.0.3" />
		<PackageReference Include="X.Web.MetaExtractor.ContentLoaders.FsHttp" Version="2.1.1" />
		<PackageReference Include="X.PagedList" Version="10.5.9" />
		<PackageReference Include="Yog.FSharp" Version="0.6.0" />
		<PackageReference Include="GraphShape" Version="1.2.1" />
		<PackageReference Include="QuikGraph" Version="2.5.0" />
		<PackageReference Include="QuikGraph.Graphviz" Version="2.5.0" />
		<PackageReference Include="QuikGraph.Serialization" Version="2.5.0" />
		<PackageReference Include="QuikGraph.Data" Version="2.5.0" />
		<PackageReference Include="QuikGraph.MSAGL" Version="2.5.0" />
		<PackageReference Include="QuikGraph.Petri" Version="2.5.0" />
		<PackageReference Include="dotNetRdf" Version="3.5.2" />
		<PackageReference Include="Iride" Version="0.6.1" />
		<PackageReference Include="FSharp.HashCollections" Version="0.3.4" />
		<PackageReference Include="Blake3" Version="3.0.1" />
		<PackageReference Include="LightningDB" Version="0.22.0" />
		<PackageReference Include="BitFaster.Caching" Version="2.6.0" />
		<PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.2" />
		<PackageReference Include="FSharp.UMX" Version="1.1.0" />
		
		<PackageReference Include="Rubjerg.Graphviz" Version="3.0.5" />

		
	</ItemGroup>
	
  <ItemGroup>
	  
    <ProjectReference Include="..\DotNetRDFSharp\DotNetRDFSharp.fsproj" />
	  
    <ProjectReference Include="..\Ergonomic_Extensions\Ergonomic_Extensions.fsproj" />
    
  </ItemGroup>

</Project>
