/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-06-21 19:00:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>ReDeFer XSD2OWL - XML Schema to OWL Web Ontology</title>\r\n");
      out.write("  <link href=\"style/rhizomik.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"logo\"><a href=\"http://rhizomik.net\"><img src=\"images/rhizomik-eye-100px.png\"/></a></div>\r\n");
      out.write("<h1>ReDeFer XSD2OWL - XML Schema to OWL Web Ontology</h1>\r\n");
      out.write("<form accept-charset=\"UTF-8\" action=\"xsd2owl\" name=\"xsd2owl\" method=\"post\" target=\"_blank\" >\r\n");
      out.write("    <p>Input XML for an XML Schema or URI pointing to one. Examples:</p>\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li><a href=\"#\" onclick=\"document.xsd2owl.xsd.value='http://www.openarchives.org/OAI/2.0/oai_dc.xsd'\">http://www.openarchives.org/OAI/2.0/oai_dc.xsd</a></li>\r\n");
      out.write("      <li><a href=\"#\" onclick=\"document.xsd2owl.xsd.value='http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd'\">http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <p><input type=\"text\" size=\"80\" name=\"xsd\" id=\"xsd\"/></p>\r\n");
      out.write("    <input type=\"submit\" name=\"Submit\" value=\"Submit\"/>\r\n");
      out.write("</form>\r\n");
      out.write("<h1>XSD to OWL API</h1>\r\n");
      out.write("<p>The base address of the service is: <b>");
      out.print(request.getRequestURL());
      out.write("xsd2owl</b></p>\r\n");
      out.write("<p>It can called using <b>GET</b>. The parameter of the service is:</p>\r\n");
      out.write("<ul>\r\n");
      out.write("    <li><b>xsd= URL</b>: an URL pointing to the XML source of the XML Schema to be processed.</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<p>Example using GET:</p>\r\n");
      out.write("<p><a target=\"_blank\" href=\"");
      out.print(request.getRequestURL());
      out.write("xsd2owl?xsd=http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd\"><b>");
      out.print(request.getRequestURL());
      out.write("xsd2owl</b>?<b>xsd</b>=http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd</a></p>\r\n");
      out.write("<h1>How does it work?</h1>\r\n");
      out.write("<p>XSD2OWL is based on an XSLT (XML Style Sheet Transformation) that performs a partial mapping from XML Schema to OWL. It is an implementation of the &quot;<a href=\"http://rhizomik.net/html/~roberto/thesis/html/Methodology.html#XMLSemanticsReuse\" target=\"_top\">XML Semantics Reuse Methodology</a>&quot; proposed in the PhD Thesis &quot;<a href=\"http://rhizomik.net/~roberto/thesis\" target=\"_top\">A Semantic Web Approach to Digital Rights Management</a>&quot;. It can be tested from the <a style=\"font-weight: bold;\" href=\"http://rhizomik.net/redefer\">ReDeFer</a> web page.</p>\r\n");
      out.write("<p>The XML Schema to OWL mapping is responsible for capturing the schema implicit semantics. This semantics are determined by the combination of XML Schema constructs. The XSD2OWL mapping is based on translating this constructs to the OWL ones that best capture their semantics. These translations are shown in Table 1.</p>\r\n");
      out.write("<p style=\"text-align: center;\"><a><strong>Table 1</strong></a><strong>.</strong> XSD2OWL translations for the XML Schema constructs and shared semantics with OWL constructs</p>\r\n");
      out.write("<table cellspacing=\"0\" cellpadding=\"5\" bordercolor=\"#000000\" border=\"1\" align=\"center\">\r\n");
      out.write("  <tbody>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"center\"><strong>XML Schema</strong></p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"center\"><strong>OWL</strong></p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"center\"><strong>Shared informal semantics</strong></p>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>element|attribute</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>rdf: Property<br />\r\n");
      out.write("        owl: DatatypeProperty<br />\r\n");
      out.write("        owl: ObjectProperty</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"left\">Named relation between nodes or nodes and values</p>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>element@substitutionGroup</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>rdfs: subPropertyOf</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"left\">Relation can appear in place of a more general one</p>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>element@type</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>rdfs: range</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"left\">The relation range kind</p>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>complexType|group<br />\r\n");
      out.write("        |attributeGroup</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>owl: Class</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"left\">Relations and contextual restrictions package</p>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>complexType//element</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>owl: Restriction</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"left\">Contextualised restriction of a relation</p>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>extension@base|<br />\r\n");
      out.write("        restriction@base</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>rdfs: subClassOf</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"left\">Package concretises the base package</p>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>@maxOccurs<br />\r\n");
      out.write("        @minOccurs</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>owl: maxCardinality<br />\r\n");
      out.write("        owl: minCardinality</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"left\">Restrict the number of occurrences of a relation</p>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>sequence<br />\r\n");
      out.write("        choice</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p>owl: intersectionOf<br />\r\n");
      out.write("        owl: unionOf</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>\r\n");
      out.write("      <p align=\"left\">Combination of relations in a context</p>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<p>The XSD2OWL mapping is quite transparent and captures a great part XML Schema semantics. The same names used for XML constructs are used for OWL ones, although in the new namespace defined for the ontology. Therefore, it produces OWL ontologies that make explicit the semantics of the corresponding XML Schemas. The only caveats are the implicit order conveyed by <em>xsd: sequence</em> and the exclusivity of <em>xsd: choice</em>.</p>\r\n");
      out.write("<p>For the first problem, <em>owl: intersectionOf</em> does not retain its operands order, there is no clear solution that retains the great level of transparency that has been achieved. The use of RDF Lists might impose order but introduces ad-hoc constructs not present in the original metadata. Moreover, as it has been demonstrated in practise, the elements' ordering does not contribute much from a semantic point of view. For the second problem, <em>owl: unionOf</em> is an inclusive union, the solution is to use the disjointness OWL construct, <em>owl: disjointWith</em>, between all union operands in order to make it exclusive.</p>\r\n");
      out.write("<h2>Example</h2>\r\n");
      out.write("<p>The first figure presents a fragment of XMLSchema that defines a &quot;grant&quot; element as a <span style=\"font-style: italic;\">xsd: choice</span>. The first choice is a <span style=\"font-style: italic;\">xsd: sequence</span> of the &quot;principal&quot;, &quot;resource&quot;, &quot;right&quot; and &quot;condition&quot; elements. Only &quot;right&quot; is mandatory, i.e. it must occur at least once. The other choice is an &quot;encriptedGrant&quot; element. Moreover, the is the &quot;validityInterval&quot; element that is declared to be a substitutionGroup of the &quot;condition&quot; element, i.e. it can appear wherever the &quot;condition&quot; element can appear. The &quot;validityInterval&quot; element is defined as a <span style=\"font-style: italic;\">xsd: sequence</span> of &quot;notBefore&quot; and &quot;notAfter&quot;, both non-mandatory.</p>\r\n");
      out.write("<p>The second figure shows the corresponding OWL mapping produced by the XSD2OWL XSL.</p>\r\n");
      out.write("<p><img width=\"402\" height=\"262\" src=\"images/XSD2OWLexample1.gif\" alt=\"XSD Model\" /> <img width=\"476\" height=\"511\" src=\"images/XSD2OWLexample2.gif\" alt=\"OWL Model\" /></p>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
