
#load "Microsoft.AspNetCore.Hosting.Abstractions.csx" 
#load "Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csx" 
#load "Microsoft.AspNetCore.WebUtilities.csx" 
#load "Microsoft.Extensions.Configuration.csx" 
#load "Microsoft.Extensions.Configuration.Binder.csx" 
#load "Microsoft.Extensions.Logging.Abstractions.csx" 
#load "Microsoft.Extensions.Options.csx" 
#load "Microsoft.Net.Http.Headers.csx" 
#load "System.Security.Cryptography.Cng.csx" 
#r "../../packages/Microsoft.AspNetCore.Server.Kestrel.Core/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll" 