
#load "Microsoft.AspNetCore.Authorization.Policy.csx" 
#load "Microsoft.AspNetCore.Hosting.Abstractions.csx" 
#load "Microsoft.AspNetCore.Http.csx" 
#load "Microsoft.AspNetCore.Http.Connections.Common.csx" 
#load "Microsoft.AspNetCore.Routing.csx" 
#load "Microsoft.AspNetCore.WebSockets.csx" 
#load "Newtonsoft.Json.csx" 
#load "System.Net.WebSockets.WebSocketProtocol.csx" 
#r "../../packages/Microsoft.AspNetCore.Http.Connections/lib/netstandard2.0/Microsoft.AspNetCore.Http.Connections.dll" 